{
    "name": "DTF Studio Admin",
    "version": "19.0.7.0.0",
    "summary": "Native Odoo administration shell and review workflows for DTF Studio",
    "category": "DTF Studio",
    "license": "LGPL-3",
    "depends": [
        "web",
        "dtf_core",
        "dtf_designer",
        "dtf_design",
        "dtf_preflight",
        "dtf_sale",
        "sale_loyalty",
        "dtf_production",
        "dtf_finance",
        "dtf_printify",
        "dtf_notifications",
        "dtf_backend_theme",
    ],
    "data": [
        "security/admin_security.xml",
        "security/ir.model.access.csv",
        "views/admin_wizards.xml",
        "views/admin_views.xml",
        "views/admin_operations_views.xml",
        "views/dashboard_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "dtf_admin/static/src/dashboard/dashboard.js",
            "dtf_admin/static/src/dashboard/dashboard.xml",
            "dtf_admin/static/src/dashboard/dashboard.scss",
        ],
    },
    "installable": True,
    "application": True,
}
