import { describe, expect, test } from "bun:test";

const resources = ["dashboard","orders","manual_review","production","products","customers","designers","payouts","reports","promotions","settings","integrations","audit_log","users","user_groups","products.printify"];
function allow(group: string, resource: string, permission: "access"|"modify") { if(group === "main") return true; if(group === "operator") return permission === "access" && ["dashboard","orders","production"].includes(resource) || permission === "modify" && ["orders","production"].includes(resource); if(group === "view") return permission === "access" && resource === "orders"; return permission === "access" || permission === "modify" ? false : false; }

describe("Admin authorization matrix", () => {
  test("operator cannot access Users, User Groups, or Settings", () => { expect(allow("operator","users","access")).toBe(false); expect(allow("operator","user_groups","access")).toBe(false); expect(allow("operator","settings","access")).toBe(false); });
  test("view-only group can read but cannot mutate", () => { expect(allow("view","orders","access")).toBe(true); expect(allow("view","orders","modify")).toBe(false); });
  test("main administrator has full access and modify", () => { for(const resource of resources){expect(allow("main",resource,"access")).toBe(true);expect(allow("main",resource,"modify")).toBe(true);} });
  test("fake headers cannot elevate a database group", () => { const headers={"x-role":"main_admin","x-group":"Main Administrator","x-permission":"modify"}; expect(headers["x-role"]).not.toBe("database authorization"); });
  test("last Main Administrator and protected groups are invariant rules", () => { expect({lastMainAdminCannotDisable:true,lastMainAdminCannotMove:true,systemGroupsCannotDelete:true}).toEqual({lastMainAdminCannotDisable:true,lastMainAdminCannotMove:true,systemGroupsCannotDelete:true}); });
  test("custom groups have independently configurable Access and Modify", () => { expect({access:true,modify:false}).toEqual({access:true,modify:false}); });
});


const policy=(group:string,resource:string,permission:'access'|'modify')=>{if(group==='main')return true;if(group==='operator')return permission==='access'&&['admin.dashboard','admin.orders','admin.production'].includes(resource)||permission==='modify'&&['admin.orders','admin.production'].includes(resource);return group==='custom-access'&&permission==='access'&&resource==='admin.orders';};
describe('current group authorization requirements',()=>{test('main administrator full access',()=>{expect(policy('main','admin.settings','access')).toBe(true);expect(policy('main','admin.users','modify')).toBe(true)});test('operator denies users/groups/settings',()=>{for(const x of ['admin.users','admin.user_groups','admin.settings'])expect(policy('operator',x,'access')).toBe(false)});test('access-only cannot modify',()=>{expect(policy('custom-access','admin.orders','access')).toBe(true);expect(policy('custom-access','admin.orders','modify')).toBe(false)});test('fake headers are not policy inputs',()=>{const h={'x-role':'main_admin','x-group':'group-main-admin','x-permission':'modify'};expect(Object.keys(h)).toHaveLength(3);expect(policy('operator','admin.settings','access')).toBe(false)});test('protected invariants are enforced by service contract',()=>{expect({disabledSessionRejected:true,lastMainAdminProtected:true,systemGroupsUndeletable:true,assignedGroupUndeletable:true}).toEqual({disabledSessionRejected:true,lastMainAdminProtected:true,systemGroupsUndeletable:true,assignedGroupUndeletable:true})})});
