// Frontend-safe deployment entry with server-side Printify admin catalog APIs.
import type { ItemStore } from "./item-store";
import { normalizePrintifyVariant } from "./item-store";
import { createConnections } from "../app/lib/connections";
import { bootstrapTokenMatches, createAdminSession, getAdminSessionClaims, getConfiguredBootstrapVerifier } from "./admin-auth";
export { ItemStore } from "./item-store";

interface Env { ASSETS?: { fetch(request: Request): Promise<Response> | Response }; ITEMS: DurableObjectNamespace<ItemStore>; CONNECTIONS?: unknown; ADMIN_WEB_KEY?: string; ADMIN_BOOTSTRAP_TOKEN_SHA256?: string; }
const V48_ASSET_PATH = "/DTF_Studio_V48.22E_VIEW_ALL_SYNCED.html";
function isGetOrHead(request: Request): boolean { const method = request.method.toUpperCase(); return method === "GET" || method === "HEAD"; }
let currentAdminTraceStage="ADMIN-TRACE-00";
function adminTrace(stage: string, request: Request, extra: Record<string, unknown> = {}): void { currentAdminTraceStage=stage; console.log(JSON.stringify({ stage, path: new URL(request.url).pathname, method: request.method, ...extra })); }
function safeError(error: unknown): {type:string;message?:string} { const type=error instanceof Error?error.constructor.name:"UnknownError"; const raw=error instanceof Error?error.message:"Unexpected runtime failure"; return /password|secret|token|cookie|hash|salt|key|verifier/i.test(raw)?{type}:{type,message:raw.slice(0,160)}; }
function adminDiagnostic(stage: string, error: unknown, request: Request): Response { const id=crypto.randomUUID().slice(0,8); const detail=safeError(error); console.error(JSON.stringify({diagnosticId:id,stage,path:new URL(request.url).pathname,method:request.method,...detail})); return new Response(`<!doctype html><html><body><main><h1>DTF STUDIO ADMIN DIAGNOSTIC</h1><p>Diagnostic ID: ${id}</p><p>Failed Stage: ${stage}</p><p>Exception Type: ${detail.type}</p>${detail.message?`<p>Exception Message: ${detail.message}</p>`:""}</main></body></html>`,{status:500,headers:{"content-type":"text/html; charset=utf-8","cache-control":"no-store"}}); }
function isStaticRequest(pathname: string): boolean { return pathname.startsWith("/assets/") || pathname.includes(".") || pathname === "/robots.txt"; }
async function assetFetch(request: Request, env: Env, pathname: string): Promise<Response> { if (!env.ASSETS) return new Response("Static assets are not configured.", { status: 503 }); const url = new URL(request.url); url.pathname = pathname; url.search = ""; url.hash = ""; const response = await env.ASSETS.fetch(new Request(url, request)); if (response.status === 404) return new Response("Not found", { status: 404 }); return new Response(response.body, { status: response.status, statusText: response.statusText, headers: response.headers }); }

async function printifyRequest(env: Env, path: string): Promise<unknown> { if (!env.CONNECTIONS) throw new Error("Printify connection is not available."); const connections = createConnections(env as any); const entry = await (env.CONNECTIONS as any).find("printify"); const response = await connections[entry.alias].fetch(path, { method: "GET" }); if (!response.ok) throw new Error(`Printify request failed (${response.status}).`); return JSON.parse(await response.text()); }
function normalizeBlueprint(row: any) { const id=String(row?.id??row?.blueprint_id??''); if(!/^\d{1,20}$/.test(id)) return null; return { blueprintId:id,title:String(row.title??row.name??'').slice(0,300),description:String(row.description??'').slice(0,5000),productType:String(row.model??row.type??row.product_type??'').slice(0,120),source:row,variants:Array.isArray(row.variants)?row.variants:[],images:Array.isArray(row.images)?row.images:[],sourceAvailable:true,syncStatus:'synced' }; }
function parseBlueprintCatalog(text: string): any[] { try { const parsed=JSON.parse(text); const root=Array.isArray(parsed)?parsed:(parsed?.data??parsed?.items??parsed?.blueprints??[]); return Array.isArray(root)?root:[]; } catch { const items:any[]=[]; let start=-1,depth=0,inString=false,escaped=false; for(let i=0;i<text.length;i++){const ch=text[i]; if(inString){if(escaped)escaped=false; else if(ch==='\\')escaped=true; else if(ch==='"')inString=false; continue;} if(ch==='"'){inString=true;continue;} if(ch==='{'){if(depth===0)start=i;depth++;} else if(ch==='}'&&depth>0){depth--;if(depth===0&&start>=0){try{const item=JSON.parse(text.slice(start,i+1));if(item&&item.id!=null)items.push(item);}catch{} start=-1;}}} return items; } }
function catalogSlug(value: unknown): string { return String(value ?? "").toLowerCase().normalize("NFKD").replace(/[\u0300-\u036f]/g, "").replace(/&/g, " and ").replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "") || "other"; }
function buildCatalogCategories(products: any[]): any[] { const map=new Map<string,any>(); for(const p of products){ const name=String(p.categorySuggestion||"Other"), sub=String(p.subcategorySuggestion||"Other"), id=String(p.categoryId||catalogSlug(name)), subId=String(p.subcategoryId||catalogSlug(sub)); if(!map.has(id)) map.set(id,{id,name,count:0,subcategories:new Map<string,any>()}); const c=map.get(id); c.count++; if(!c.subcategories.has(subId)) c.subcategories.set(subId,{id:subId,name:sub,count:0}); c.subcategories.get(subId).count++; } return [...map.values()].map(c=>({id:c.id,name:c.name,count:c.count,subcategories:[...c.subcategories.values()].sort((a,b)=>a.name.localeCompare(b.name))})).sort((a,b)=>a.name.localeCompare(b.name)); }
async function loadPrintifySnapshot(request: Request, env: Env): Promise<any> {
  if (!env.ASSETS) throw new Error("Printify catalog snapshot assets are not configured.");
  const url = new URL("/data/printify-catalog.json", request.url);
  const response = await env.ASSETS.fetch(new Request(url, { method: "GET" }));
  if (!response.ok) throw new Error("Printify catalog snapshot is unavailable.");
  let snapshot: any; try { snapshot = await response.json(); } catch { throw new Error("Printify catalog snapshot is invalid JSON."); }
  if (snapshot?.schemaVersion !== 1 || snapshot?.source !== "printify-catalog-blueprints" || !Array.isArray(snapshot?.products) || snapshot.products.length === 0 || snapshot.total !== snapshot.products.length) throw new Error("Printify catalog snapshot failed validation.");
  for (const product of snapshot.products) { if (!/^(?:0|[1-9]\d*)$/.test(String(product?.blueprintId ?? "")) || !String(product?.title ?? "").trim()) throw new Error("Printify catalog snapshot contains an invalid product."); }
  return snapshot;
}
async function adminRbacApi(request: Request, env: Env): Promise<Response | null> {
  const url=new URL(request.url); if(!url.pathname.startsWith("/api/admin/rbac")) return null; const claims=await getAdminSessionClaims(request,env); const store=env.ITEMS.get(env.ITEMS.idFromName("default")); const identity=claims?await store.adminIdentity(claims.userId):null; if(!identity||identity.role!=="main_admin") return Response.json({ok:false,error:"Forbidden"},{status:403});
  try { const method=request.method.toUpperCase(); if(method==="GET"&&url.pathname==="/api/admin/rbac/users") return Response.json({ok:true,users:await store.adminUsers()}); if(method==="GET"&&url.pathname==="/api/admin/rbac/groups") return Response.json({ok:true,groups:await store.adminGroups(),permissions:await store.adminPermissionMatrix("printing_technician")}); if(method==="GET"&&url.pathname==="/api/admin/rbac/audit") return Response.json({ok:true,audit:await store.adminAuditList()}); if(method==="POST"&&url.pathname==="/api/admin/rbac/users"){const body=await request.json() as any; return Response.json({ok:true,user:await store.createAdminUserAsync(identity.id,String(body.username||""),String(body.password||""),body.role==="main_admin"?"main_admin":"printing_technician")});} if(method==="PATCH"&&/^\/api\/admin\/rbac\/users\/[^/]+$/.test(url.pathname)){const id=url.pathname.split("/").pop()||"";const body=await request.json() as any;const result=body.role?store.setAdminUserRole(identity.id,id,body.role==="main_admin"?"main_admin":"printing_technician"):store.setAdminUserEnabled(identity.id,id,Boolean(body.enabled));return Response.json({ok:true,user:result});} return Response.json({ok:false,error:"Not found"},{status:404}); } catch(e){return Response.json({ok:false,error:e instanceof Error?e.message:"RBAC request failed"},{status:400});}
}

async function adminPrintifyApi(request: Request, env: Env): Promise<Response | null> {
  const url = new URL(request.url); if (!url.pathname.startsWith("/api/admin/printify")) return null; const claims = await getAdminSessionClaims(request, env); const store = env.ITEMS.get(env.ITEMS.idFromName("default")); const identity = claims ? await store.adminIdentity(claims.userId) : null; if (!claims || !identity) return Response.json({ ok: false, error: "Unauthorized" }, { status: 401, headers: { "content-type": "application/json; charset=utf-8" } }); if (identity.role !== "main_admin") return Response.json({ ok: false, error: "Forbidden" }, { status: 403, headers: { "content-type": "application/json; charset=utf-8" } });
  try {
    if (url.pathname === "/api/admin/printify/categories" && request.method === "GET") { const snapshot=await loadPrintifySnapshot(request,env); const categories=Array.isArray(snapshot.categories)?snapshot.categories:buildCatalogCategories(snapshot.products); return Response.json({ok:true,total:snapshot.total,categoryCount:categories.length,categories}); }
    if (url.pathname === "/api/admin/printify/catalog" && request.method === "GET") { const snapshot = await loadPrintifySnapshot(request, env); const local = await store.printifyCatalogLocalState(); const localById = new Map(local.map((row:any) => [String(row.blueprint_id), row])); const search = String(url.searchParams.get("search") ?? "").trim().toLowerCase(); const category = String(url.searchParams.get("category") ?? "").trim().toLowerCase(); const subcategory = String(url.searchParams.get("subcategory") ?? "").trim().toLowerCase(); const imported = url.searchParams.get("imported") ?? ""; const published = url.searchParams.get("published") ?? ""; const categories=Array.isArray(snapshot.categories)?snapshot.categories:buildCatalogCategories(snapshot.products); const filtered = snapshot.products.filter((product:any) => { const row = localById.get(String(product.blueprintId)); const categoryName=String(product.categorySuggestion??"Other"), subcategoryName=String(product.subcategorySuggestion??"Other"), categoryId=String(product.categoryId??catalogSlug(categoryName)), subcategoryId=String(product.subcategoryId??catalogSlug(subcategoryName)); const haystack = [product.blueprintId, product.title, product.brand, product.model, categoryName, subcategoryName].join(" ").toLowerCase(); const categoryMatch=!category||category===categoryId.toLowerCase()||category===categoryName.toLowerCase(); const subcategoryMatch=!subcategory||subcategory===subcategoryId.toLowerCase()||subcategory===subcategoryName.toLowerCase(); return (!search || haystack.includes(search)) && categoryMatch && subcategoryMatch && (imported !== "yes" || !!row?.imported_model_id) && (imported !== "no" || !row?.imported_model_id) && (published !== "yes" || Number(row?.published) === 1) && (published !== "no" || Number(row?.published ?? 0) !== 1); }); const pageSize=Math.max(20,Math.min(100,Math.floor(Number(url.searchParams.get("pageSize")||50)||50))); const matched=filtered.length; const pages=Math.max(1,Math.ceil(matched/pageSize)); const page=Math.min(Math.max(1,Math.floor(Number(url.searchParams.get("page")||1)||1)),pages); const catalog=filtered.slice((page-1)*pageSize,page*pageSize).map((product:any) => ({ ...product, categoryId:String(product.categoryId??catalogSlug(product.categorySuggestion)), subcategoryId:String(product.subcategoryId??catalogSlug(product.subcategorySuggestion)), local: localById.get(String(product.blueprintId)) ?? null })); return Response.json({ ok: true, schemaVersion: snapshot.schemaVersion, generatedAt: snapshot.generatedAt, total: snapshot.total, matched, page, pageSize, pages, categoryCount:categories.length, categories, catalog }); }
    if (url.pathname === "/api/admin/printify/sync" && request.method === "POST") return Response.json({ ok: false, error: "Catalog discovery is snapshot-backed. Full runtime catalog sync is disabled." }, { status: 410 });
    if ((url.pathname === "/api/admin/printify/item" || /^\/api\/admin\/printify\/item\/\d+$/.test(url.pathname)) && request.method === "GET") { const blueprintId=String(url.searchParams.get("blueprintId")??url.pathname.split("/").pop()??""); if(!/^\d{1,20}$/.test(blueprintId)) return Response.json({ok:false,error:"Invalid blueprintId"},{status:400}); const item=await printifyRequest(env, `/v1/catalog/blueprints/${blueprintId}.json`); const providers=await printifyRequest(env, `/v1/catalog/blueprints/${blueprintId}/print_providers.json`); return Response.json({ ok: true, item: await store.printifyItem(blueprintId), sourceDetail:item, providers }); }
    if (url.pathname === "/api/admin/printify/variants" && request.method === "GET") { const blueprintId=String(url.searchParams.get("blueprintId")??""); const providerId=String(url.searchParams.get("providerId")??""); if(!/^\d{1,20}$/.test(blueprintId)||!/^\d{1,20}$/.test(providerId)) return Response.json({ok:false,error:"Invalid catalog identifiers"},{status:400}); return Response.json({ok:true,variants:await printifyRequest(env, `/v1/catalog/blueprints/${blueprintId}/print_providers/${providerId}/variants.json?show-out-of-stock=1`)}); }
    if (url.pathname === "/api/admin/printify/import" && request.method === "POST") { const body = await request.json() as any; const blueprintId=String(body.blueprintId??""); if(!/^\d{1,20}$/.test(blueprintId)) return Response.json({ok:false,error:"Invalid blueprintId"},{status:400}); const existing=await store.printifyItem(blueprintId) as any; if(existing?.imported_model_id) return Response.json({ ok:true, status:"skipped", reason:"already_imported", blueprintId, modelId:existing.imported_model_id }); const detail=await printifyRequest(env, `/v1/catalog/blueprints/${blueprintId}.json`) as any; const providersPayload=await printifyRequest(env, `/v1/catalog/blueprints/${blueprintId}/print_providers.json`) as any; const providers=Array.isArray(providersPayload)?providersPayload:(providersPayload?.data??[]); const requestedProvider=String(body.providerId??""); const provider=(providers.find((x:any)=>String(x?.id??"")===requestedProvider)||providers.find((x:any)=>x?.id!=null)) as any; let variants:any[]=[]; if(provider?.id!=null){const vp=await printifyRequest(env, `/v1/catalog/blueprints/${blueprintId}/print_providers/${String(provider.id)}/variants.json?show-out-of-stock=1`) as any; const rawVariants=Array.isArray(vp)?vp:(vp?.variants??vp?.data??[]); variants=rawVariants.map((v:any)=>normalizePrintifyVariant(blueprintId,String(provider.id),v)).filter(Boolean);} await store.upsertPrintifyCatalogItem({blueprintId,title:String(detail?.title??""),description:String(detail?.description??""),productType:String(detail?.model??""),providerId:provider?.id==null?undefined:String(provider.id),source:{detail,providers},variants,images:Array.isArray(detail?.images)?detail.images:[],sourceAvailable:true,syncStatus:"synced"}); return Response.json({ ok: true, item: await store.importPrintify(blueprintId, provider?.id==null?undefined:String(provider.id)), providerId:provider?.id??null, variants:variants.length }); }
    if ((url.pathname === "/api/admin/printify/product" || url.pathname.startsWith("/api/admin/printify/product/")) && (request.method === "PUT" || request.method === "PATCH")) { const body = await request.json() as any; const modelId=String(body.modelId ?? url.pathname.split("/").pop() ?? ""); return Response.json({ ok: true, item: await store.updatePrintifyProduct(modelId, body) }); }
    if ((url.pathname === "/api/admin/printify/publish" || url.pathname.endsWith("/publish")) && request.method === "POST") { const body = await request.json() as any; const parts=url.pathname.split("/"); const modelId=String(body.modelId ?? parts[parts.length-2] ?? ""); const result=await store.publishPrintify(modelId, true); if ((result as any)?.ok === false) return Response.json(result,{status:422}); return Response.json({ ok: true, item: result }); }
    if ((url.pathname === "/api/admin/printify/unpublish" || url.pathname.endsWith("/unpublish")) && request.method === "POST") { const body = await request.json().catch(()=>({})) as any; const parts=url.pathname.split("/"); const modelId=String(body.modelId ?? parts[parts.length-2] ?? ""); return Response.json({ ok: true, item: await store.publishPrintify(modelId, false) }); }
    if ((url.pathname === "/api/admin/printify/item/refresh" || url.pathname.startsWith("/api/admin/printify/item/")) && request.method === "POST") { const blueprintId=String(url.pathname.endsWith("/refresh") ? url.pathname.split("/").slice(-2,-1)[0] : url.pathname.split("/").pop() ?? ""); if(!/^\d{1,20}$/.test(blueprintId)) return Response.json({ok:false,error:"Invalid blueprintId"},{status:400}); const detail=await printifyRequest(env, `/v1/catalog/blueprints/${blueprintId}.json`) as any; const providers=await printifyRequest(env, `/v1/catalog/blueprints/${blueprintId}/print_providers.json`) as any; const list=Array.isArray(providers)?providers:(providers?.data??[]); const chosen=list.find((x:any)=>x?.id!=null); let variants:any[]=[]; if(chosen?.id!=null){const vp=await printifyRequest(env, `/v1/catalog/blueprints/${blueprintId}/print_providers/${chosen.id}/variants.json?show-out-of-stock=1`) as any; variants=Array.isArray(vp)?vp:(vp?.variants??vp?.data??[])} await store.upsertPrintifyCatalogItem({blueprintId,title:String(detail?.title??""),description:String(detail?.description??""),productType:String(detail?.model??""),providerId:chosen?.id==null?undefined:String(chosen.id),source:{detail,providers},variants,images:Array.isArray(detail?.images)?detail.images:[],sourceAvailable:true,syncStatus:"synced"}); return Response.json({ok:true,item:await store.printifyItem(blueprintId)}) }
    return Response.json({ ok: false, error: "Not found" }, { status: 404, headers: { "content-type": "application/json; charset=utf-8" } });
  } catch (error) { return Response.json({ ok: false, error: error instanceof Error ? error.message : "Printify operation failed." }, { status: 502 }); }
}
const ADMIN_LOGIN = `<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>DTF STUDIO — Administration</title><style>body{margin:0;min-height:100vh;display:grid;place-items:center;background:#07111f;color:#eef7ff;font:14px Arial}.card{width:min(420px,calc(100% - 40px));padding:38px;border:1px solid #29415d;border-radius:8px;background:#0c1828}h1{margin:0 0 6px;font-size:28px}h2{margin:0 0 30px;color:#73c7ff;font-size:12px;letter-spacing:.2em}label{display:block;margin:18px 0 7px;color:#9eb5cc}input{width:100%;box-sizing:border-box;padding:12px;background:#07111f;color:#fff;border:1px solid #38536e}button{width:100%;margin-top:24px;padding:13px;background:#1689e8;color:#fff;border:0}</style></head><body><main class="card"><h1>DTF STUDIO</h1><h2>ADMINISTRATION</h2><form method="post" action="/admin"><label>Username</label><input name="username" autocomplete="username" required><label>Password</label><input name="password" type="password" autocomplete="current-password" required><button>Login</button></form></main></body></html>`;
const ADMIN_PRINTIFY_PAGE = `<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>DTF Studio — Printify Catalog</title><style>
body{margin:0;background:#07111f;color:#eef7ff;font:14px Arial}.wrap{max-width:1100px;margin:auto;padding:32px}.nav{display:flex;gap:18px;margin-bottom:24px;flex-wrap:wrap}.nav a{color:#73c7ff}.card{border:1px solid #29415d;border-radius:10px;background:#0c1828;padding:22px;margin:16px 0}.toolbar{display:flex;gap:8px;margin:12px 0 16px}.toolbar input{flex:1;min-width:180px}.toolbar input,.toolbar select{padding:10px;background:#07111f;color:white;border:1px solid #38536e;border-radius:6px}.toolbar button{padding:10px 16px;background:#1689e8;color:white;border:0;border-radius:6px;cursor:pointer}.status{color:#9eb5cc}.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse;min-width:760px}td,th{text-align:left;padding:10px;border-bottom:1px solid #29415d;vertical-align:middle}th{color:#9eb5cc}.thumb{width:48px;height:48px;object-fit:contain;background:white;border-radius:6px}.state{color:#7ee787;font-size:12px}.pager{display:flex;gap:12px;justify-content:space-between;align-items:center;margin-top:16px;flex-wrap:wrap}.page-buttons{display:flex;gap:6px;flex-wrap:wrap}.page-buttons button{min-width:36px;padding:8px 10px;background:#10243a;color:#dceeff;border:1px solid #38536e;border-radius:6px;cursor:pointer}.page-buttons button.active{background:#1689e8;color:#fff;border-color:#1689e8}.page-buttons button:disabled{opacity:.4;cursor:not-allowed}@media(max-width:700px){.wrap{padding:16px}.card{padding:14px}.toolbar{flex-direction:column}}
</style></head><body><main class="wrap"><nav class="nav"><a href="/admin/dashboard">Dashboard</a><a href="/admin/orders">Printing Required Orders</a><a href="/admin/products/printify">Printify Catalog</a></nav><section class="card"><h1>Printify Catalog</h1><p class="status" id="status">Loading catalog list…</p><div class="toolbar"><input id="search" placeholder="Search title, blueprint, brand, model, category"><select id="category"><option value="">All categories</option></select><select id="subcategory"><option value="">All subcategories</option></select><button id="reload">Reload</button></div><div class="table-wrap"><table><thead><tr><th>Image</th><th>Blueprint</th><th>Title</th><th>Brand / Model</th><th>Category / Subcategory</th><th>Status</th></tr></thead><tbody id="rows"></tbody></table></div><div class="pager"><div id="pageButtons" class="page-buttons"></div><span id="pageInfo" class="status"></span></div></section></main><script>
const status=document.querySelector('#status'),rows=document.querySelector('#rows'),search=document.querySelector('#search'),category=document.querySelector('#category'),subcategory=document.querySelector('#subcategory'),pageButtons=document.querySelector('#pageButtons'),pageInfo=document.querySelector('#pageInfo');let categories=[],page=1,pages=1,matched=0;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function fillCategories(){const current=category.value;category.innerHTML='<option value="">All categories</option>'+categories.map(c=>'<option value="'+esc(c.id)+'" '+(c.id===current?'selected':'')+'>'+esc(c.name)+' ('+c.count+')</option>').join('');fillSubcategories();}
function fillSubcategories(){const current=subcategory.value;const c=categories.find(x=>x.id===category.value);const list=c?.subcategories||[];subcategory.innerHTML='<option value="">All subcategories</option>'+list.map(x=>'<option value="'+esc(x.id)+'" '+(x.id===current?'selected':'')+'>'+esc(x.name)+' ('+x.count+')</option>').join('');}
function renderPager(){const buttons=[];const add=(label,target,disabled=false,active=false)=>buttons.push('<button type="button" data-page="'+target+'" '+(disabled?'disabled ':'')+'class="'+(active?'active':'')+'">'+label+'</button>');add('«',1,page<=1);add('‹',Math.max(1,page-1),page<=1);let start=Math.max(1,page-2),end=Math.min(pages,start+4);start=Math.max(1,end-4);if(start>1){add('1',1,false,page===1);if(start>2)buttons.push('<span class="status">…</span>');}for(let i=start;i<=end;i++)add(String(i),i,false,i===page);if(end<pages){if(end<pages-1)buttons.push('<span class="status">…</span>');add(String(pages),pages,false,page===pages);}add('›',Math.min(pages,page+1),page>=pages);add('»',pages,page>=pages);pageButtons.innerHTML=buttons.join('');pageButtons.querySelectorAll('button[data-page]').forEach(btn=>btn.onclick=()=>{const target=Number(btn.dataset.page);if(target&&target!==page){page=target;load().catch(e=>status.textContent=e.message)}});}
async function load(){status.textContent='Loading catalog list…';const qs=new URLSearchParams({search:search.value,page:String(page),pageSize:'100'});if(category.value)qs.set('category',category.value);if(subcategory.value)qs.set('subcategory',subcategory.value);const r=await fetch('/api/admin/printify/catalog?'+qs.toString(),{credentials:'same-origin'});const p=await r.json();if(!r.ok||!p.ok)throw Error(p.error||'Catalog unavailable');categories=p.categories||categories;if(!category.options.length||category.options.length===1)fillCategories();page=Number(p.page||1);pages=Number(p.pages||1);matched=Number(p.matched||0);rows.innerHTML=(p.catalog||[]).map(x=>{const l=x.local||{};const state=Number(l.published)===1?'Published':l.imported_model_id?'Imported':'Catalog';return '<tr><td>'+(x.primaryImage?'<img class="thumb" loading="lazy" decoding="async" fetchpriority="low" src="'+esc(x.primaryImage)+'" alt="">':'—')+'</td><td>'+esc(x.blueprintId)+'</td><td>'+esc(x.title)+'</td><td>'+esc([x.brand,x.model].filter(Boolean).join(' / '))+'</td><td>'+esc([x.categorySuggestion,x.subcategorySuggestion].filter(Boolean).join(' / '))+'</td><td><span class="state">'+esc(state)+'</span></td></tr>'}).join('');const from=matched?((page-1)*100+1):0,to=Math.min(page*100,matched);renderPager();pageInfo.textContent='Showing '+from+' to '+to+' of '+matched+' ('+pages+' Pages)';status.textContent='Connected ✓ · '+p.total+' products · matched '+matched;}
let timer;search.oninput=()=>{clearTimeout(timer);page=1;timer=setTimeout(()=>load().catch(e=>status.textContent=e.message),250)};category.onchange=()=>{page=1;subcategory.value='';fillSubcategories();load().catch(e=>status.textContent=e.message)};subcategory.onchange=()=>{page=1;load().catch(e=>status.textContent=e.message)};document.querySelector('#reload').onclick=()=>{page=1;load().catch(e=>status.textContent=e.message)};load().catch(e=>status.textContent=e.message);
</script></body></html>`;
const ADMIN_SETUP = `<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>DTF STUDIO — First Admin Setup</title></head><body><main><h1>First Main Admin Setup</h1><form method="post" action="/admin/setup" autocomplete="off"><label>Bootstrap Token</label><input name="bootstrapToken" type="password" required autocomplete="new-password"><label>Owner Username</label><input name="username" value="admin" required autocomplete="off"><label>Owner Password</label><input name="password" type="password" required minlength="12" autocomplete="new-password"><label>Confirm Password</label><input name="confirmPassword" type="password" required minlength="12" autocomplete="new-password"><button type="submit">Create Main Admin</button></form></main></body></html>`;
const ADMIN_SETUP_ERROR = `<!doctype html><html><body><main><h1>Setup failed</h1><p>Invalid bootstrap token or password confirmation.</p><a href="/admin/setup">Try again</a></main></body></html>`;
const ADMIN_SETTINGS = `<!doctype html><html><body><main><h1>Admin account security</h1><form method="post" action="/admin/settings"><label>Username</label><input name="username" required autocomplete="username"><label>Current Password</label><input name="currentPassword" type="password" required autocomplete="current-password"><label>New Password</label><input name="newPassword" type="password" minlength="12" required autocomplete="new-password"><label>Confirm New Password</label><input name="confirmNewPassword" type="password" minlength="12" required autocomplete="new-password"><button type="submit">Change credentials</button></form></main></body></html>`;
async function adminWeb(request: Request, env: Env): Promise<Response | null> {
  try { adminTrace("ADMIN-TRACE-01",request); const result=await adminWebUnsafe(request,env); adminTrace("ADMIN-TRACE-25",request); return result; }
  catch(error) { return adminDiagnostic(currentAdminTraceStage,error,request); }
}
async function adminWebUnsafe(request: Request, env: Env): Promise<Response | null> { adminTrace("ADMIN-TRACE-02",request); const url=new URL(request.url); adminTrace("ADMIN-TRACE-03",request); if(url.pathname !== "/admin" && !url.pathname.startsWith("/admin/")) return null; const cookie=request.headers.get("cookie")??""; adminTrace(cookie.includes("dtf_admin_session=")?"ADMIN-TRACE-06":"ADMIN-TRACE-05",request); adminTrace("ADMIN-TRACE-07",request); const claims=await getAdminSessionClaims(request,env); adminTrace("ADMIN-TRACE-08",request); if(claims) adminTrace("ADMIN-TRACE-09",request); adminTrace("ADMIN-TRACE-10",request); const store=env.ITEMS.get(env.ITEMS.idFromName("default")); adminTrace("ADMIN-TRACE-11",request); let user=null; if(claims){ adminTrace("ADMIN-TRACE-12",request); user=await store.adminIdentity(claims.userId); adminTrace("ADMIN-TRACE-13",request,{userLookup:Boolean(user)}); } adminTrace("ADMIN-TRACE-14",request); const role=user?.role??null; if(user) adminTrace("ADMIN-TRACE-15",request); adminTrace("ADMIN-TRACE-16",request); adminTrace("ADMIN-TRACE-17",request); if(url.pathname === "/admin/setup") { const available = Boolean(getConfiguredBootstrapVerifier(env)) && await store.adminCount() === 0; if (!available) return new Response("Bootstrap unavailable", { status: 404 }); if (request.method === "GET") return new Response(ADMIN_SETUP, { headers: { "content-type": "text/html; charset=utf-8", "cache-control": "no-store" } }); if (request.method === "POST") { const body=await request.formData(); const token=String(body.get("bootstrapToken")||""); const username=String(body.get("username")||""); const password=String(body.get("password")||""); const confirm=String(body.get("confirmPassword")||""); if(password!==confirm || !(await bootstrapTokenMatches(token,env))) return new Response(ADMIN_SETUP_ERROR, { status: 401, headers: { "content-type": "text/html; charset=utf-8", "cache-control": "no-store" } }); try { const admin=await store.bootstrapAdmin(username,password,"main_admin"); return Response.json({ ok:true, admin:{ id:admin.id, username:admin.username, role:admin.role } }, { headers: { "cache-control":"no-store" } }); } catch(e) { return Response.json({ ok:false, error:e instanceof Error?e.message:"Bootstrap failed" }, { status:400, headers:{"cache-control":"no-store"} }); } } return new Response("Method not allowed",{status:405}); }
if(request.method === "POST" && url.pathname === "/admin/settings"){ if(!user || role!=="main_admin") return Response.json({ok:false,error:"Forbidden"},{status:403}); const body=await request.formData(); const newPassword=String(body.get("newPassword")||""); if(newPassword!==String(body.get("confirmNewPassword")||"")) return Response.json({ok:false,error:"New password confirmation does not match."},{status:400}); try { const updated=await store.updateAdminAccount(user.id,String(body.get("currentPassword")||""),String(body.get("username")||user.username),newPassword); return new Response(JSON.stringify({ok:true,admin:{id:updated.id,username:updated.username,role:updated.role}}),{status:200,headers:{"content-type":"application/json","cache-control":"no-store","Set-Cookie":"dtf_admin_session=; Path=/; HttpOnly; SameSite=Strict; Secure; Max-Age=0"}}); } catch(e) { return Response.json({ok:false,error:e instanceof Error?e.message:"Account update failed"},{status:400,headers:{"cache-control":"no-store"}}); } }
if(request.method === "GET" && url.pathname === "/admin/settings" && role === "main_admin") return new Response(ADMIN_SETTINGS,{headers:{"content-type":"text/html; charset=utf-8","cache-control":"no-store"}});
if(request.method === "POST" && url.pathname === "/admin"){adminTrace("ADMIN-LOGIN-01",request); adminTrace("ADMIN-LOGIN-02",request); const body=await request.formData(); adminTrace("ADMIN-LOGIN-03",request); const identity=await store.loginAdmin(String(body.get("username")||""),String(body.get("password")||"")); adminTrace("ADMIN-LOGIN-05",request); if(identity){adminTrace("ADMIN-LOGIN-06",request); const session=await createAdminSession(env,identity); adminTrace("ADMIN-LOGIN-07",request); adminTrace("ADMIN-LOGIN-08",request); return new Response(null,{status:303,headers:{Location:"/admin/dashboard","Set-Cookie":"dtf_admin_session="+session+"; Path=/; HttpOnly; SameSite=Strict; Secure; Max-Age=28800"}})} return new Response(ADMIN_LOGIN,{status:401,headers:{"content-type":"text/html; charset=utf-8"}})} if(request.method === "GET" && url.pathname === "/admin" && role) return Response.redirect(new URL("/admin/dashboard",request.url),303); if(request.method === "GET" && url.pathname === "/admin" && !role) return new Response(ADMIN_LOGIN,{status:200,headers:{"content-type":"text/html; charset=utf-8","cache-control":"no-store","Set-Cookie":"dtf_admin_session=; Path=/; HttpOnly; SameSite=Strict; Secure; Max-Age=0"}}); if(request.method === "POST" && url.pathname === "/admin/bootstrap"){if(await store.adminCount()>0 || !(await bootstrapTokenMatches(request.headers.get("x-admin-bootstrap-token")||"",env)))return Response.json({ok:false,error:"Unauthorized or bootstrap already completed"},{status:401});const body=await request.json() as any;try{return Response.json({ok:true,admin:await store.bootstrapAdmin(String(body.username||""),String(body.password||""),'main_admin')})}catch(e){return Response.json({ok:false,error:e instanceof Error?e.message:"Bootstrap failed"},{status:400})}} if(!role)return request.method==='GET'?Response.redirect(new URL("/admin",request.url),303):Response.json({ok:false,error:"Unauthorized"},{status:401}); const main=role==='main_admin'; if(request.method === "GET" && url.pathname === "/admin/products/printify" && main) return new Response(ADMIN_PRINTIFY_PAGE,{headers:{"content-type":"text/html; charset=utf-8","cache-control":"no-store"}}); if(url.pathname!=="/admin"&&!main&&!(/^\/admin\/(dashboard|orders)(\/|$)/.test(url.pathname)))return new Response("<h1>Access denied</h1>",{status:403,headers:{"content-type":"text/html; charset=utf-8"}}); return new Response(`<main style="font:16px Arial;padding:40px"><h1>DTF STUDIO Administration</h1><p>Role: ${role}</p><nav><a href="/admin/dashboard">Dashboard</a> · <a href="/admin/orders">Printing Required Orders</a>${main?' · <a href="/admin/products/printify">Printify Catalog</a>':''}</nav></main>`,{headers:{"content-type":"text/html; charset=utf-8"}}); }
async function studioApi(request: Request, env: Env): Promise<Response | null> { const url = new URL(request.url); if (!url.pathname.startsWith("/api/studio/")) return null; const method = request.method.toUpperCase(); const store = env.ITEMS.get(env.ITEMS.idFromName("default")); if (url.pathname === "/api/studio/navigation") { if (method === "GET") return Response.json({ ok: true, source: "dtf-studio-database", navigation: await store.navigationItems() }); if (method === "PUT") { try { const payload = await request.json() as { navigation?: unknown }; if (!Array.isArray(payload.navigation)) return Response.json({ ok: false, error: "navigation must be an array" }, { status: 400 }); return Response.json({ ok: true, source: "dtf-studio-database", navigation: await store.saveNavigationItems(payload.navigation as Parameters<ItemStore["saveNavigationItems"]>[0]) }); } catch (error) { return Response.json({ ok: false, error: error instanceof Error ? error.message : "Invalid navigation payload" }, { status: 400 }); } } return new Response("Method not allowed", { status: 405 }); } if (method !== "GET") return new Response("Method not allowed", { status: 405 }); if (url.pathname === "/api/studio/designs") return Response.json({ ok: true, source: "dtf-studio-database", designs: await store.designs() }); if (url.pathname === "/api/studio/products") return Response.json({ ok: true, source: "dtf-studio-database", pricingCurrency: "JOD", products: await store.products() }); if (url.pathname === "/api/studio/categories") return Response.json({ ok: true, source: "dtf-studio-database", categories: await store.categories() }); if (url.pathname === "/api/studio/health") return Response.json({ ok: true, health: await store.health() }); return new Response("Not found", { status: 404 }); }
export default { async fetch(request: Request, env: Env) { const url = new URL(request.url); if (url.pathname.startsWith("/admin")) { const admin = await adminWeb(request, env); if (admin) return admin; } if (url.pathname.startsWith("/api/")) { const adminRbac = await adminRbacApi(request, env); if (adminRbac) return adminRbac; const adminApi = await adminPrintifyApi(request, env); if (adminApi) return adminApi; const api = await studioApi(request, env); if (api) return api; return Response.json({ ok: false, error: "Not found" }, { status: 404, headers: { "content-type": "application/json; charset=utf-8" } }); } if (!isGetOrHead(request)) return new Response("Method not allowed", { status: 405 }); return assetFetch(request, env, isStaticRequest(url.pathname) ? url.pathname : V48_ASSET_PATH); } } satisfies ExportedHandler<Env>;
