// Frontend-safe deployment entry with server-side Printify admin catalog APIs.
import type { ItemStore } from "./item-store";
import { normalizePrintifyVariant } from "./item-store";
import { createConnections } from "../app/lib/connections";
import { bootstrapTokenMatches, createAdminSession, getAdminSessionClaims, getConfiguredBootstrapVerifier } from "./admin-auth";
export { ItemStore } from "./item-store";

interface Env { ASSETS?: { fetch(request: Request): Promise<Response> | Response }; ITEMS: DurableObjectNamespace<ItemStore>; CONNECTIONS?: unknown; ADMIN_WEB_KEY?: string; ADMIN_BOOTSTRAP_TOKEN_SHA256?: string; }
const V48_ASSET_PATH = "/DTF_Studio_V48.22E_VIEW_ALL_SYNCED.html";
function isGetOrHead(request: Request): boolean { const method = request.method.toUpperCase(); return method === "GET" || method === "HEAD"; }
let currentAdminTraceStage="ADMIN-TRACE-00";
function adminTrace(stage: string, request: Request, extra: Record<string, unknown> = {}): void { currentAdminTraceStage=stage; console.log(JSON.stringify({ stage, path: new URL(request.url).pathname, method: request.method, ...extra })); }
function safeError(error: unknown): {type:string;message?:string} { const type=error instanceof Error?error.constructor.name:"UnknownError"; const raw=error instanceof Error?error.message:"Unexpected runtime failure"; return /password|secret|token|cookie|hash|salt|key|verifier/i.test(raw)?{type}:{type,message:raw.slice(0,160)}; }
function adminDiagnostic(stage: string, error: unknown, request: Request): Response { const id=crypto.randomUUID().slice(0,8); const detail=safeError(error); console.error(JSON.stringify({diagnosticId:id,stage,path:new URL(request.url).pathname,method:request.method,...detail})); return new Response(`<!doctype html><html><body><main><h1>DTF STUDIO ADMIN DIAGNOSTIC</h1><p>Diagnostic ID: ${id}</p><p>Failed Stage: ${stage}</p><p>Exception Type: ${detail.type}</p>${detail.message?`<p>Exception Message: ${detail.message}</p>`:""}</main></body></html>`,{status:500,headers:{"content-type":"text/html; charset=utf-8","cache-control":"no-store"}}); }
function isStaticRequest(pathname: string): boolean { return pathname.startsWith("/assets/") || pathname.includes(".") || pathname === "/robots.txt"; }
async function assetFetch(request: Request, env: Env, pathname: string): Promise<Response> { if (!env.ASSETS) return new Response("Static assets are not configured.", { status: 503 }); const url = new URL(request.url); url.pathname = pathname; url.search = ""; url.hash = ""; const response = await env.ASSETS.fetch(new Request(url, request)); if (response.status === 404) return new Response("Not found", { status: 404 }); return new Response(response.body, { status: response.status, statusText: response.statusText, headers: response.headers }); }

async function printifyRequest(env: Env, path: string): Promise<unknown> { if (!env.CONNECTIONS) throw new Error("Printify connection is not available."); const connections = createConnections(env as any); const entry = await (env.CONNECTIONS as any).find("printify"); const response = await connections[entry.alias].fetch(path, { method: "GET" }); if (!response.ok) throw new Error(`Printify request failed (${response.status}).`); return JSON.parse(await response.text()); }
function normalizeBlueprint(row: any) { const id=String(row?.id??row?.blueprint_id??''); if(!/^\d{1,20}$/.test(id)) return null; return { blueprintId:id,title:String(row.title??row.name??'').slice(0,300),description:String(row.description??'').slice(0,5000),productType:String(row.model??row.type??row.product_type??'').slice(0,120),source:row,variants:Array.isArray(row.variants)?row.variants:[],images:Array.isArray(row.images)?row.images:[],sourceAvailable:true,syncStatus:'synced' }; }
function parseBlueprintCatalog(text: string): any[] { try { const parsed=JSON.parse(text); const root=Array.isArray(parsed)?parsed:(parsed?.data??parsed?.items??parsed?.blueprints??[]); return Array.isArray(root)?root:[]; } catch { const items:any[]=[]; let start=-1,depth=0,inString=false,escaped=false; for(let i=0;i<text.length;i++){const ch=text[i]; if(inString){if(escaped)escaped=false; else if(ch==='\\')escaped=true; else if(ch==='"')inString=false; continue;} if(ch==='"'){inString=true;continue;} if(ch==='{'){if(depth===0)start=i;depth++;} else if(ch==='}'&&depth>0){depth--;if(depth===0&&start>=0){try{const item=JSON.parse(text.slice(start,i+1));if(item&&item.id!=null)items.push(item);}catch{} start=-1;}}} return items; } }
async function loadPrintifySnapshot(request: Request, env: Env): Promise<any> {
  if (!env.ASSETS) throw new Error("Printify catalog snapshot assets are not configured.");
  const url = new URL("/data/printify-catalog.json", request.url);
  const response = await env.ASSETS.fetch(new Request(url, { method: "GET" }));
  if (!response.ok) throw new Error("Printify catalog snapshot is unavailable.");
  let snapshot: any; try { snapshot = await response.json(); } catch { throw new Error("Printify catalog snapshot is invalid JSON."); }
  if (snapshot?.schemaVersion !== 1 || snapshot?.source !== "printify-catalog-blueprints" || !Array.isArray(snapshot?.products) || snapshot.products.length === 0 || snapshot.total !== snapshot.products.length) throw new Error("Printify catalog snapshot failed validation.");
  for (const product of snapshot.products) { if (!/^(?:0|[1-9]\d*)$/.test(String(product?.blueprintId ?? "")) || !String(product?.title ?? "").trim()) throw new Error("Printify catalog snapshot contains an invalid product."); }
  return snapshot;
}
async function adminPrintifyApi(request: Request, env: Env): Promise<Response | null> {
  const url = new URL(request.url); if (!url.pathname.startsWith("/api/admin/printify")) return null; const claims = await getAdminSessionClaims(request, env); const store = env.ITEMS.get(env.ITEMS.idFromName("default")); const identity = claims ? await store.adminIdentity(claims.userId) : null; if (!claims || !identity) return Response.json({ ok: false, error: "Unauthorized" }, { status: 401, headers: { "content-type": "application/json; charset=utf-8" } }); if (identity.role !== "main_admin") return Response.json({ ok: false, error: "Forbidden" }, { status: 403, headers: { "content-type": "application/json; charset=utf-8" } });
  try {
    if (url.pathname === "/api/admin/printify/catalog" && request.method === "GET") { const snapshot = await loadPrintifySnapshot(request, env); const local = await store.printifyCatalogLocalState(); const localById = new Map(local.map((row:any) => [String(row.blueprint_id), row])); const search = String(url.searchParams.get("search") ?? "").trim().toLowerCase(); const imported = url.searchParams.get("imported") ?? ""; const published = url.searchParams.get("published") ?? ""; const catalog = snapshot.products.filter((product:any) => { const row = localById.get(String(product.blueprintId)); const haystack = [product.blueprintId, product.title, product.brand, product.model, product.categorySuggestion, product.subcategorySuggestion].join(" ").toLowerCase(); return (!search || haystack.includes(search)) && (imported !== "yes" || !!row?.imported_model_id) && (imported !== "no" || !row?.imported_model_id) && (published !== "yes" || Number(row?.published) === 1) && (published !== "no" || Number(row?.published ?? 0) !== 1); }).map((product:any) => ({ ...product, local: localById.get(String(product.blueprintId)) ?? null })); return Response.json({ ok: true, schemaVersion: snapshot.schemaVersion, generatedAt: snapshot.generatedAt, total: snapshot.total, catalog }); }
    if (url.pathname === "/api/admin/printify/sync" && request.method === "POST") return Response.json({ ok: false, error: "Catalog discovery is snapshot-backed. Full runtime catalog sync is disabled." }, { status: 410 });
    if ((url.pathname === "/api/admin/printify/item" || /^\/api\/admin\/printify\/item\/\d+$/.test(url.pathname)) && request.method === "GET") { const blueprintId=String(url.searchParams.get("blueprintId")??url.pathname.split("/").pop()??""); if(!/^\d{1,20}$/.test(blueprintId)) return Response.json({ok:false,error:"Invalid blueprintId"},{status:400}); const item=await printifyRequest(env, `/v1/catalog/blueprints/${blueprintId}.json`); const providers=await printifyRequest(env, `/v1/catalog/blueprints/${blueprintId}/print_providers.json`); return Response.json({ ok: true, item: await store.printifyItem(blueprintId), sourceDetail:item, providers, categories: await store.categories({ role: "admin" }) }); }
    if (url.pathname === "/api/admin/printify/variants" && request.method === "GET") { const blueprintId=String(url.searchParams.get("blueprintId")??""); const providerId=String(url.searchParams.get("providerId")??""); if(!/^\d{1,20}$/.test(blueprintId)||!/^\d{1,20}$/.test(providerId)) return Response.json({ok:false,error:"Invalid catalog identifiers"},{status:400}); return Response.json({ok:true,variants:await printifyRequest(env, `/v1/catalog/blueprints/${blueprintId}/print_providers/${providerId}/variants.json?show-out-of-stock=1`)}); }
    if (url.pathname === "/api/admin/printify/import" && request.method === "POST") { const body = await request.json() as any; const blueprintId=String(body.blueprintId??""); if(!/^\d{1,20}$/.test(blueprintId)) return Response.json({ok:false,error:"Invalid blueprintId"},{status:400}); const existing=await store.printifyItem(blueprintId) as any; if(existing?.imported_model_id) return Response.json({ ok:true, status:"skipped", reason:"already_imported", blueprintId, modelId:existing.imported_model_id }); const detail=await printifyRequest(env, `/v1/catalog/blueprints/${blueprintId}.json`) as any; const providersPayload=await printifyRequest(env, `/v1/catalog/blueprints/${blueprintId}/print_providers.json`) as any; const providers=Array.isArray(providersPayload)?providersPayload:(providersPayload?.data??[]); const requestedProvider=String(body.providerId??""); if(!/^\d{1,20}$/.test(requestedProvider)) return Response.json({ok:false,error:"A valid Print Provider is required."},{status:400}); const provider=providers.find((x:any)=>String(x?.id??"")===requestedProvider) as any; if(!provider) return Response.json({ok:false,error:"Selected Print Provider is not available for this product."},{status:422}); const vp=await printifyRequest(env, `/v1/catalog/blueprints/${blueprintId}/print_providers/${requestedProvider}/variants.json?show-out-of-stock=1`) as any; const rawVariants=Array.isArray(vp)?vp:(vp?.variants??vp?.data??[]); const variants=rawVariants.map((v:any)=>normalizePrintifyVariant(blueprintId,requestedProvider,v)).filter(Boolean); if(!variants.length) return Response.json({ok:false,error:"Selected Print Provider has no usable variants."},{status:422}); await store.upsertPrintifyCatalogItem({blueprintId,title:String(detail?.title??""),description:String(detail?.description??""),productType:String(detail?.model??""),providerId:requestedProvider,source:{detail,providers},variants,images:Array.isArray(detail?.images)?detail.images:[],sourceAvailable:true,syncStatus:"synced"}); return Response.json({ ok: true, item: await store.importPrintify(blueprintId, requestedProvider), providerId:requestedProvider, variants:variants.length }); }
    if ((url.pathname === "/api/admin/printify/product" || url.pathname.startsWith("/api/admin/printify/product/")) && (request.method === "PUT" || request.method === "PATCH")) { const body = await request.json() as any; const modelId=String(body.modelId ?? url.pathname.split("/").pop() ?? ""); return Response.json({ ok: true, item: await store.updatePrintifyProduct(modelId, body) }); }
    if ((url.pathname === "/api/admin/printify/publish" || url.pathname.endsWith("/publish")) && request.method === "POST") { const body = await request.json() as any; const parts=url.pathname.split("/"); const modelId=String(body.modelId ?? parts[parts.length-2] ?? ""); const result=await store.publishPrintify(modelId, true); if ((result as any)?.ok === false) return Response.json(result,{status:422}); return Response.json({ ok: true, item: result }); }
    if ((url.pathname === "/api/admin/printify/unpublish" || url.pathname.endsWith("/unpublish")) && request.method === "POST") { const body = await request.json().catch(()=>({})) as any; const parts=url.pathname.split("/"); const modelId=String(body.modelId ?? parts[parts.length-2] ?? ""); return Response.json({ ok: true, item: await store.publishPrintify(modelId, false) }); }
    if (/^\/api\/admin\/printify\/item\/\d+\/refresh$/.test(url.pathname) && request.method === "POST") {
      const blueprintId=String(url.pathname.split("/").slice(-2,-1)[0]??"");
      const body=await request.json().catch(()=>({})) as any;
      const local=await store.printifyItem(blueprintId) as any;
      if(!local?.imported_model_id) return Response.json({ok:false,error:"Imported product not found."},{status:404});
      const detail=await printifyRequest(env, `/v1/catalog/blueprints/${blueprintId}.json`) as any;
      const providersPayload=await printifyRequest(env, `/v1/catalog/blueprints/${blueprintId}/print_providers.json`) as any;
      const providers=Array.isArray(providersPayload)?providersPayload:(providersPayload?.data??[]);
      const providerId=String(body.providerId??local.selected_provider_id??local.provider_id??"");
      const provider=providers.find((x:any)=>String(x?.id??"")===providerId);
      if(!provider) { await store.markPrintifySourceUnavailable(blueprintId,"provider_unavailable"); return Response.json({ok:false,error:"Selected Print Provider is no longer available. Product was made unavailable locally."},{status:422}); }
      const vp=await printifyRequest(env, `/v1/catalog/blueprints/${blueprintId}/print_providers/${providerId}/variants.json?show-out-of-stock=1`) as any;
      const rawVariants=Array.isArray(vp)?vp:(vp?.variants??vp?.data??[]);
      const normalized=rawVariants.map((v:any)=>normalizePrintifyVariant(blueprintId,providerId,v)).filter(Boolean);
      if(!normalized.length) { await store.markPrintifySourceUnavailable(blueprintId,"no_usable_variants"); return Response.json({ok:false,error:"Selected Print Provider has no usable variants. Product was made unavailable locally."},{status:422}); }
      await store.upsertPrintifyCatalogItem({blueprintId,title:String(detail?.title??""),description:String(detail?.description??""),productType:String(detail?.model??""),providerId,source:{detail,providers},variants:normalized,images:Array.isArray(detail?.images)?detail.images:[],sourceAvailable:true,syncStatus:"synced"});
      const item=await store.refreshImportedPrintifySource(blueprintId,providerId,normalized);
      return Response.json({ok:true,item,providerId,variants:normalized.length});
    }
    return Response.json({ ok: false, error: "Not found" }, { status: 404, headers: { "content-type": "application/json; charset=utf-8" } });
  } catch (error) { return Response.json({ ok: false, error: error instanceof Error ? error.message : "Printify operation failed." }, { status: 502 }); }
}
const ADMIN_LOGIN = `<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>DTF STUDIO — Administration</title><style>body{margin:0;min-height:100vh;display:grid;place-items:center;background:#07111f;color:#eef7ff;font:14px Arial}.card{width:min(420px,calc(100% - 40px));padding:38px;border:1px solid #29415d;border-radius:8px;background:#0c1828}h1{margin:0 0 6px;font-size:28px}h2{margin:0 0 30px;color:#73c7ff;font-size:12px;letter-spacing:.2em}label{display:block;margin:18px 0 7px;color:#9eb5cc}input{width:100%;box-sizing:border-box;padding:12px;background:#07111f;color:#fff;border:1px solid #38536e}button{width:100%;margin-top:24px;padding:13px;background:#1689e8;color:#fff;border:0}</style></head><body><main class="card"><h1>DTF STUDIO</h1><h2>ADMINISTRATION</h2><form method="post" action="/admin"><label>Username</label><input name="username" autocomplete="username" required><label>Password</label><input name="password" type="password" autocomplete="current-password" required><button>Login</button></form></main></body></html>`;
const ADMIN_PRINTIFY_PAGE = `<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>DTF Studio — Printify Products</title><style>
body{margin:0;background:#07111f;color:#eef7ff;font:14px Arial}.wrap{max-width:1240px;margin:auto;padding:28px}.nav{display:flex;gap:18px;margin-bottom:22px;flex-wrap:wrap}.nav a{color:#73c7ff}.card{border:1px solid #29415d;border-radius:10px;background:#0c1828;padding:20px;margin:14px 0}button{padding:10px 15px;background:#1689e8;color:#fff;border:0;border-radius:6px;cursor:pointer}button.secondary{background:#29415d}button.danger{background:#a33}button:disabled{opacity:.45;cursor:not-allowed}input,select,textarea{box-sizing:border-box;padding:9px;background:#07111f;color:#fff;border:1px solid #38536e;border-radius:4px}input[type=text],input[type=number],textarea,select.wide{width:100%}textarea{min-height:92px;resize:vertical}.status{color:#9eb5cc}.ok{color:#7ee787}.warn{color:#ffd866}.error{color:#ff8b8b}.actions{display:flex;gap:9px;flex-wrap:wrap;align-items:center}.filters{display:grid;grid-template-columns:minmax(220px,1fr) 150px 150px auto;gap:9px}.detail-grid{display:grid;grid-template-columns:minmax(190px,280px) 1fr;gap:22px}.detail-image{width:100%;max-height:300px;object-fit:contain;border-radius:8px;background:#07111f}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.field label{display:block;margin-bottom:5px;color:#9eb5cc}.result{margin-top:12px;padding:11px;border:1px solid #29415d;border-radius:6px;background:#07111f}.image-choices{display:flex;gap:9px;overflow:auto;padding:8px 0}.image-choice{display:block;border:1px solid #29415d;border-radius:6px;padding:5px;min-width:82px;text-align:center}.image-choice img{width:72px;height:72px;object-fit:contain;display:block}.variants{max-height:330px;overflow:auto;border:1px solid #29415d;border-radius:6px;padding:8px}.variant{display:grid;grid-template-columns:auto 1fr auto;gap:8px;padding:7px;border-bottom:1px solid #1d3047}.variant:last-child{border-bottom:0}table{width:100%;border-collapse:collapse}td,th{text-align:left;padding:9px;border-bottom:1px solid #29415d;vertical-align:top}pre{white-space:pre-wrap;max-height:300px;overflow:auto;background:#07111f;padding:10px;border-radius:6px}
@media(max-width:800px){.wrap{padding:14px}.detail-grid,.form-grid,.filters{grid-template-columns:1fr}table{font-size:12px}}
</style></head><body><main class="wrap"><nav class="nav"><a href="/admin/dashboard">Dashboard</a><a href="/admin/orders">Printing Required Orders</a><a href="/admin/products/printify">Printify Products</a></nav>
<section class="card"><h1>Printify Products</h1><p class="status" id="status">Loading catalog snapshot…</p><div class="filters"><input id="search" placeholder="Search title, blueprint, brand, model, category"><select id="imported"><option value="">All import states</option><option value="yes">Imported</option><option value="no">Not imported</option></select><select id="published"><option value="">All publish states</option><option value="yes">Published</option><option value="no">Not published</option></select><button id="reload">Reload</button></div>
<table><thead><tr><th>Image</th><th>Blueprint</th><th>Title</th><th>Brand / Model</th><th>Category</th><th>Local status</th><th>Action</th></tr></thead><tbody id="rows"></tbody></table></section>
<section class="card" id="detail" hidden></section></main><script>
const status=document.querySelector('#status'),rows=document.querySelector('#rows'),detail=document.querySelector('#detail'),search=document.querySelector('#search'),importedFilter=document.querySelector('#imported'),publishedFilter=document.querySelector('#published');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function call(path,opt){const r=await fetch(path,opt);const p=await r.json().catch(()=>({ok:false,error:'Invalid server response'}));if(!r.ok||p.ok===false){const msg=Array.isArray(p.errors)&&p.errors.length?p.errors.join(' | '):(p.error||'Request failed');throw Error(msg)}return p}
function imageUrl(image){return typeof image==='string'?image:String(image?.src||image?.url||'')}
async function load(){const qs=new URLSearchParams();if(search.value.trim())qs.set('search',search.value.trim());if(importedFilter.value)qs.set('imported',importedFilter.value);if(publishedFilter.value)qs.set('published',publishedFilter.value);const p=await call('/api/admin/printify/catalog?'+qs.toString());rows.innerHTML=(p.catalog||[]).map(x=>{const l=x.local||{};const state=Number(l.published)===1?'Published':l.imported_model_id?'Imported':'Not imported';const img=x.primaryImage?'<img src="'+esc(x.primaryImage)+'" width="48" height="48" style="object-fit:contain" alt="">':'—';return '<tr><td>'+img+'</td><td>'+esc(x.blueprintId)+'</td><td>'+esc(x.title)+'</td><td>'+esc([x.brand,x.model].filter(Boolean).join(' / '))+'</td><td>'+esc([x.categorySuggestion,x.subcategorySuggestion].filter(Boolean).join(' / '))+'</td><td>'+esc(state)+'</td><td><button data-id="'+esc(x.blueprintId)+'">Open</button></td></tr>'}).join('');status.textContent='Catalog snapshot · '+p.total+' products · showing '+(p.catalog||[]).length+' · Generated: '+p.generatedAt;rows.querySelectorAll('button[data-id]').forEach(b=>b.onclick=()=>openProduct(b.dataset.id))}
async function openProduct(id){detail.hidden=false;detail.innerHTML='<p class="status">Loading product…</p>';try{const p=await call('/api/admin/printify/item?blueprintId='+encodeURIComponent(id));renderProduct(id,p)}catch(e){detail.innerHTML='<p class="error">'+esc(e.message)+'</p>'}}
function renderProduct(id,p){const ps=Array.isArray(p.providers)?p.providers:(p.providers?.data||[]);const source=p.sourceDetail||{};const local=p.item||{};const categories=Array.isArray(p.categories)?p.categories:[];const imported=!!local.imported_model_id;const title=source.title||local.source_title||('Blueprint '+id);const sourceImages=(Array.isArray(source.images)?source.images:[]).map(imageUrl).filter(Boolean);const selectedProvider=String(local.selected_provider_id||local.provider_id||'');const providerOptions=ps.map(x=>'<option value="'+esc(x.id)+'" '+(String(x.id)===selectedProvider?'selected':'')+'>'+esc(x.title||x.name||'Provider')+' (ID '+esc(x.id)+')</option>').join('');const hero=local.display_image||sourceImages[0]||'';let html='<div class="detail-grid"><div>'+(hero?'<img class="detail-image" src="'+esc(hero)+'" alt="">':'<div class="status">No image available</div>')+'</div><div><h2>'+esc(title)+'</h2><p>Blueprint '+esc(id)+'</p><p>Status: <strong>'+(Number(local.published)===1?'Published':imported?'Imported — Draft':'Not imported')+'</strong></p><div class="field"><label>Print Provider</label><select class="wide" id="provider" '+(imported?'disabled':'')+'>'+providerOptions+'</select></div><div class="actions" style="margin-top:12px"><button id="loadVariants">Load provider variants</button>'+(imported?'<button class="secondary" id="refreshSource">Refresh Source</button>':'<button id="importProduct">Import Product</button>')+'</div><div id="actionResult"></div><div id="remoteVariants"></div></div></div>';
if(imported){const lv=Array.isArray(local.localVariants)?local.localVariants:[];const cats=categories.map(c=>'<option value="'+esc(c.id)+'" '+(String(c.id)===String(local.category_id||'')?'selected':'')+'>'+esc(c.nameEn)+' / '+esc(c.nameAr)+'</option>').join('');const imgs=sourceImages.length?'<div class="image-choices">'+sourceImages.map((u,i)=>'<label class="image-choice"><img src="'+esc(u)+'" alt=""><input type="radio" name="displayImage" value="'+esc(u)+'" '+((local.display_image===u)||(!local.display_image&&i===0)?'checked':'')+'> Display</label>').join('')+'</div>':'<p class="status">No Printify images available.</p>';const variants=lv.length?'<div class="variants">'+lv.map(v=>'<label class="variant"><input type="checkbox" class="variantToggle" value="'+esc(v.id)+'" '+(v.enabled?'checked':'')+' '+(v.sourceAvailable===false?'disabled':'')+'><span>'+esc(v.sourceTitle||[v.color,v.size].filter(Boolean).join(' / ')||v.sku)+'</span><span>'+(v.sourceAvailable===false?'<span class="error">Unavailable</span>':'<span class="status">'+esc([v.color,v.size].filter(Boolean).join(' / '))+'</span>')+'</span></label>').join('')+'</div>':'<p class="warn">No local variants found. Refresh/import data before publishing.</p>';html+='<hr style="border-color:#29415d;margin:22px 0"><h3>DTF Studio Product Settings</h3><div class="form-grid"><div class="field"><label>English Title *</label><input type="text" id="titleEn" value="'+esc(local.title_en||'')+'"></div><div class="field"><label>Arabic Title *</label><input type="text" id="titleAr" dir="rtl" value="'+esc(local.title_ar||'')+'"></div><div class="field"><label>English Description *</label><textarea id="descriptionEn">'+esc(local.description_en||'')+'</textarea></div><div class="field"><label>Arabic Description *</label><textarea id="descriptionAr" dir="rtl">'+esc(local.description_ar||'')+'</textarea></div><div class="field"><label>DTF Studio Category</label><select class="wide" id="categoryId">'+cats+'</select></div><div class="field"><label>Customer Price (JOD) *</label><input type="number" min="0" step="0.01" id="price" value="'+esc(local.customer_price_jod==null?'':Number(local.customer_price_jod)/100)+'"></div></div><div class="field" style="margin-top:12px"><label>Main Display Image *</label>'+imgs+'</div><label style="display:block;margin:12px 0"><input type="checkbox" id="printDream" '+(Number(local.print_your_dream)!==0?'checked':'')+'> Available in Print Your Dream</label><h4>Enabled Variants *</h4>'+variants+'<div class="actions" style="margin-top:14px"><button id="saveProduct">Save Product</button>'+(Number(local.published)===1?'<button class="danger" id="unpublishProduct">Unpublish</button>':'<button id="publishProduct">Publish</button>')+'</div><div id="saveResult"></div>'}
detail.innerHTML=html;const provider=document.querySelector('#provider'),remote=document.querySelector('#remoteVariants'),result=document.querySelector('#actionResult');document.querySelector('#loadVariants').onclick=async()=>{const providerId=provider.value;if(!providerId){remote.innerHTML='<p class="error">No provider selected.</p>';return}remote.innerHTML='<p class="status">Loading variants…</p>';try{const q=await call('/api/admin/printify/variants?blueprintId='+encodeURIComponent(id)+'&providerId='+encodeURIComponent(providerId));const variants=Array.isArray(q.variants)?q.variants:(q.variants?.variants??q.variants?.data??[]);remote.innerHTML='<p>Provider '+esc(providerId)+' · '+variants.length+' variants</p><pre>'+esc(JSON.stringify(variants.slice(0,20),null,2))+'</pre>'}catch(e){remote.innerHTML='<p class="error">'+esc(e.message)+'</p>'}};
if(imported){const refresh=document.querySelector('#refreshSource');refresh.onclick=async()=>{const providerId=selectedProvider||provider.value;if(!providerId){result.innerHTML='<div class="result error">No provider selected.</div>';return}refresh.disabled=true;result.innerHTML='<div class="result status">Refreshing source data without overwriting DTF Studio edits…</div>';try{const r=await call('/api/admin/printify/item/'+encodeURIComponent(id)+'/refresh',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({providerId})});result.innerHTML='<div class="result ok">Source refreshed · '+esc(r.variants||0)+' variants.</div>';await load();await openProduct(id)}catch(e){refresh.disabled=false;result.innerHTML='<div class="result error">'+esc(e.message)+'</div>'}}}
if(!imported){document.querySelector('#importProduct').onclick=async()=>{const providerId=provider.value;if(!providerId){result.innerHTML='<div class="result error">Select a provider first.</div>';return}const btn=document.querySelector('#importProduct');btn.disabled=true;result.innerHTML='<div class="result status">Importing selected product…</div>';try{const r=await call('/api/admin/printify/import',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({blueprintId:id,providerId})});if(r.status==='skipped'||r.reason==='already_imported')result.innerHTML='<div class="result warn">SKIPPED — ALREADY IMPORTED. Existing product was not changed.</div>';else result.innerHTML='<div class="result ok">Imported successfully · '+esc(r.variants||0)+' variants.</div>';await load();await openProduct(id)}catch(e){btn.disabled=false;result.innerHTML='<div class="result error">'+esc(e.message)+'</div>'}};return}
const saveResult=document.querySelector('#saveResult');const payload=()=>({titleEn:document.querySelector('#titleEn').value,titleAr:document.querySelector('#titleAr').value,descriptionEn:document.querySelector('#descriptionEn').value,descriptionAr:document.querySelector('#descriptionAr').value,categoryId:document.querySelector('#categoryId').value,customerPriceJod:document.querySelector('#price').value,displayImage:(document.querySelector('input[name=displayImage]:checked')||{}).value||null,printYourDream:document.querySelector('#printDream').checked,selectedProviderId:selectedProvider||provider.value,enabledVariants:Array.from(document.querySelectorAll('.variantToggle:checked')).map(x=>x.value)});
async function save(){saveResult.innerHTML='<div class="result status">Saving…</div>';const r=await call('/api/admin/printify/product/'+encodeURIComponent(local.imported_model_id),{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify(payload())});saveResult.innerHTML='<div class="result ok">Product settings saved.</div>';return r}
document.querySelector('#saveProduct').onclick=async()=>{try{await save();await load();await openProduct(id)}catch(e){saveResult.innerHTML='<div class="result error">'+esc(e.message)+'</div>'}};
const pub=document.querySelector('#publishProduct');if(pub)pub.onclick=async()=>{try{await save();saveResult.innerHTML='<div class="result status">Validating and publishing…</div>';await call('/api/admin/printify/publish',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({modelId:local.imported_model_id})});saveResult.innerHTML='<div class="result ok">Published successfully.</div>';await load();await openProduct(id)}catch(e){saveResult.innerHTML='<div class="result error">'+esc(e.message)+'</div>'}};
const unpub=document.querySelector('#unpublishProduct');if(unpub)unpub.onclick=async()=>{try{await call('/api/admin/printify/unpublish',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({modelId:local.imported_model_id})});saveResult.innerHTML='<div class="result warn">Product unpublished.</div>';await load();await openProduct(id)}catch(e){saveResult.innerHTML='<div class="result error">'+esc(e.message)+'</div>'}}
}
let timer;search.oninput=()=>{clearTimeout(timer);timer=setTimeout(()=>load().catch(e=>status.textContent=e.message),250)};importedFilter.onchange=()=>load().catch(e=>status.textContent=e.message);publishedFilter.onchange=()=>load().catch(e=>status.textContent=e.message);document.querySelector('#reload').onclick=()=>load().catch(e=>status.textContent=e.message);load().catch(e=>status.textContent=e.message);
</script></body></html>`;
const ADMIN_SETUP = `<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>DTF STUDIO — First Admin Setup</title></head><body><main><h1>First Main Admin Setup</h1><form method="post" action="/admin/setup" autocomplete="off"><label>Bootstrap Token</label><input name="bootstrapToken" type="password" required autocomplete="new-password"><label>Owner Username</label><input name="username" value="admin" required autocomplete="off"><label>Owner Password</label><input name="password" type="password" required minlength="12" autocomplete="new-password"><label>Confirm Password</label><input name="confirmPassword" type="password" required minlength="12" autocomplete="new-password"><button type="submit">Create Main Admin</button></form></main></body></html>`;
const ADMIN_SETUP_ERROR = `<!doctype html><html><body><main><h1>Setup failed</h1><p>Invalid bootstrap token or password confirmation.</p><a href="/admin/setup">Try again</a></main></body></html>`;
const ADMIN_SETTINGS = `<!doctype html><html><body><main><h1>Admin account security</h1><form method="post" action="/admin/settings"><label>Username</label><input name="username" required autocomplete="username"><label>Current Password</label><input name="currentPassword" type="password" required autocomplete="current-password"><label>New Password</label><input name="newPassword" type="password" minlength="12" required autocomplete="new-password"><label>Confirm New Password</label><input name="confirmNewPassword" type="password" minlength="12" required autocomplete="new-password"><button type="submit">Change credentials</button></form></main></body></html>`;
async function adminWeb(request: Request, env: Env): Promise<Response | null> {
  try { adminTrace("ADMIN-TRACE-01",request); const result=await adminWebUnsafe(request,env); adminTrace("ADMIN-TRACE-25",request); return result; }
  catch(error) { return adminDiagnostic(currentAdminTraceStage,error,request); }
}
async function adminWebUnsafe(request: Request, env: Env): Promise<Response | null> { adminTrace("ADMIN-TRACE-02",request); const url=new URL(request.url); adminTrace("ADMIN-TRACE-03",request); if(url.pathname !== "/admin" && !url.pathname.startsWith("/admin/")) return null; const cookie=request.headers.get("cookie")??""; adminTrace(cookie.includes("dtf_admin_session=")?"ADMIN-TRACE-06":"ADMIN-TRACE-05",request); adminTrace("ADMIN-TRACE-07",request); const claims=await getAdminSessionClaims(request,env); adminTrace("ADMIN-TRACE-08",request); if(claims) adminTrace("ADMIN-TRACE-09",request); adminTrace("ADMIN-TRACE-10",request); const store=env.ITEMS.get(env.ITEMS.idFromName("default")); adminTrace("ADMIN-TRACE-11",request); let user=null; if(claims){ adminTrace("ADMIN-TRACE-12",request); user=await store.adminIdentity(claims.userId); adminTrace("ADMIN-TRACE-13",request,{userLookup:Boolean(user)}); } adminTrace("ADMIN-TRACE-14",request); const role=user?.role??null; if(user) adminTrace("ADMIN-TRACE-15",request); adminTrace("ADMIN-TRACE-16",request); adminTrace("ADMIN-TRACE-17",request); if(url.pathname === "/admin/setup") { const available = Boolean(getConfiguredBootstrapVerifier(env)) && await store.adminCount() === 0; if (!available) return new Response("Bootstrap unavailable", { status: 404 }); if (request.method === "GET") return new Response(ADMIN_SETUP, { headers: { "content-type": "text/html; charset=utf-8", "cache-control": "no-store" } }); if (request.method === "POST") { const body=await request.formData(); const token=String(body.get("bootstrapToken")||""); const username=String(body.get("username")||""); const password=String(body.get("password")||""); const confirm=String(body.get("confirmPassword")||""); if(password!==confirm || !(await bootstrapTokenMatches(token,env))) return new Response(ADMIN_SETUP_ERROR, { status: 401, headers: { "content-type": "text/html; charset=utf-8", "cache-control": "no-store" } }); try { const admin=await store.bootstrapAdmin(username,password,"main_admin"); return Response.json({ ok:true, admin:{ id:admin.id, username:admin.username, role:admin.role } }, { headers: { "cache-control":"no-store" } }); } catch(e) { return Response.json({ ok:false, error:e instanceof Error?e.message:"Bootstrap failed" }, { status:400, headers:{"cache-control":"no-store"} }); } } return new Response("Method not allowed",{status:405}); }
if(request.method === "POST" && url.pathname === "/admin/settings"){ if(!user || role!=="main_admin") return Response.json({ok:false,error:"Forbidden"},{status:403}); const body=await request.formData(); const newPassword=String(body.get("newPassword")||""); if(newPassword!==String(body.get("confirmNewPassword")||"")) return Response.json({ok:false,error:"New password confirmation does not match."},{status:400}); try { const updated=await store.updateAdminAccount(user.id,String(body.get("currentPassword")||""),String(body.get("username")||user.username),newPassword); return new Response(JSON.stringify({ok:true,admin:{id:updated.id,username:updated.username,role:updated.role}}),{status:200,headers:{"content-type":"application/json","cache-control":"no-store","Set-Cookie":"dtf_admin_session=; Path=/; HttpOnly; SameSite=Strict; Secure; Max-Age=0"}}); } catch(e) { return Response.json({ok:false,error:e instanceof Error?e.message:"Account update failed"},{status:400,headers:{"cache-control":"no-store"}}); } }
if(request.method === "GET" && url.pathname === "/admin/settings" && role === "main_admin") return new Response(ADMIN_SETTINGS,{headers:{"content-type":"text/html; charset=utf-8","cache-control":"no-store"}});
if(request.method === "POST" && url.pathname === "/admin"){adminTrace("ADMIN-LOGIN-01",request); adminTrace("ADMIN-LOGIN-02",request); const body=await request.formData(); adminTrace("ADMIN-LOGIN-03",request); const identity=await store.loginAdmin(String(body.get("username")||""),String(body.get("password")||"")); adminTrace("ADMIN-LOGIN-05",request); if(identity){adminTrace("ADMIN-LOGIN-06",request); const session=await createAdminSession(env,identity); adminTrace("ADMIN-LOGIN-07",request); adminTrace("ADMIN-LOGIN-08",request); return new Response(null,{status:303,headers:{Location:"/admin/dashboard","Set-Cookie":"dtf_admin_session="+session+"; Path=/; HttpOnly; SameSite=Strict; Secure; Max-Age=28800"}})} return new Response(ADMIN_LOGIN,{status:401,headers:{"content-type":"text/html; charset=utf-8"}})} if(request.method === "GET" && url.pathname === "/admin" && role) return Response.redirect(new URL("/admin/dashboard",request.url),303); if(request.method === "GET" && url.pathname === "/admin" && !role) return new Response(ADMIN_LOGIN,{status:200,headers:{"content-type":"text/html; charset=utf-8","cache-control":"no-store","Set-Cookie":"dtf_admin_session=; Path=/; HttpOnly; SameSite=Strict; Secure; Max-Age=0"}}); if(request.method === "POST" && url.pathname === "/admin/bootstrap"){if(await store.adminCount()>0 || !(await bootstrapTokenMatches(request.headers.get("x-admin-bootstrap-token")||"",env)))return Response.json({ok:false,error:"Unauthorized or bootstrap already completed"},{status:401});const body=await request.json() as any;try{return Response.json({ok:true,admin:await store.bootstrapAdmin(String(body.username||""),String(body.password||""),'main_admin')})}catch(e){return Response.json({ok:false,error:e instanceof Error?e.message:"Bootstrap failed"},{status:400})}} if(!role)return request.method==='GET'?Response.redirect(new URL("/admin",request.url),303):Response.json({ok:false,error:"Unauthorized"},{status:401}); const main=role==='main_admin'; if(request.method === "GET" && url.pathname === "/admin/products/printify" && main) return new Response(ADMIN_PRINTIFY_PAGE,{headers:{"content-type":"text/html; charset=utf-8","cache-control":"no-store"}}); if(url.pathname!=="/admin"&&!main&&!(/^\/admin\/(dashboard|orders)(\/|$)/.test(url.pathname)))return new Response("<h1>Access denied</h1>",{status:403,headers:{"content-type":"text/html; charset=utf-8"}}); return new Response(`<main style="font:16px Arial;padding:40px"><h1>DTF STUDIO Administration</h1><p>Role: ${role}</p><nav><a href="/admin/dashboard">Dashboard</a> · <a href="/admin/orders">Printing Required Orders</a>${main?' · <a href="/admin/products/printify">Printify Catalog</a>':''}</nav></main>`,{headers:{"content-type":"text/html; charset=utf-8"}}); }
async function studioApi(request: Request, env: Env): Promise<Response | null> { const url = new URL(request.url); if (!url.pathname.startsWith("/api/studio/")) return null; const method = request.method.toUpperCase(); const store = env.ITEMS.get(env.ITEMS.idFromName("default")); if (url.pathname === "/api/studio/navigation") { if (method === "GET") return Response.json({ ok: true, source: "dtf-studio-database", navigation: await store.navigationItems() }); if (method === "PUT") { try { const payload = await request.json() as { navigation?: unknown }; if (!Array.isArray(payload.navigation)) return Response.json({ ok: false, error: "navigation must be an array" }, { status: 400 }); return Response.json({ ok: true, source: "dtf-studio-database", navigation: await store.saveNavigationItems(payload.navigation as Parameters<ItemStore["saveNavigationItems"]>[0]) }); } catch (error) { return Response.json({ ok: false, error: error instanceof Error ? error.message : "Invalid navigation payload" }, { status: 400 }); } } return new Response("Method not allowed", { status: 405 }); } if (method !== "GET") return new Response("Method not allowed", { status: 405 }); if (url.pathname === "/api/studio/designs") return Response.json({ ok: true, source: "dtf-studio-database", designs: await store.designs() }); if (url.pathname === "/api/studio/products") return Response.json({ ok: true, source: "dtf-studio-database", pricingCurrency: "JOD", products: await store.products() }); if (url.pathname === "/api/studio/categories") return Response.json({ ok: true, source: "dtf-studio-database", categories: await store.categories() }); if (url.pathname === "/api/studio/health") return Response.json({ ok: true, health: await store.health() }); return new Response("Not found", { status: 404 }); }
export default { async fetch(request: Request, env: Env) { const url = new URL(request.url); if (url.pathname.startsWith("/admin")) { const admin = await adminWeb(request, env); if (admin) return admin; } if (url.pathname.startsWith("/api/")) { const adminApi = await adminPrintifyApi(request, env); if (adminApi) return adminApi; const api = await studioApi(request, env); if (api) return api; return Response.json({ ok: false, error: "Not found" }, { status: 404, headers: { "content-type": "application/json; charset=utf-8" } }); } if (!isGetOrHead(request)) return new Response("Method not allowed", { status: 405 }); return assetFetch(request, env, isStaticRequest(url.pathname) ? url.pathname : V48_ASSET_PATH); } } satisfies ExportedHandler<Env>;
