// Frontend-safe deployment entry with server-side Printify admin catalog APIs.
import type { ItemStore } from "./item-store";
import { normalizePrintifyVariant } from "./item-store";
import { createConnections } from "../app/lib/connections";
import { bootstrapTokenMatches, createAdminSession, getAdminSessionClaims, getConfiguredBootstrapVerifier } from "./admin-auth";
import { localizeAdminHtml } from "./admin-i18n";
import { ADMIN_ROUTE_REGISTRY, adminCanonicalRouteForPath, adminRouteForPath } from "./admin-routes";
export { ItemStore } from "./item-store";

interface Env { ASSETS?: { fetch(request: Request): Promise<Response> | Response }; ITEMS: DurableObjectNamespace<ItemStore>; CONNECTIONS?: unknown; ADMIN_WEB_KEY?: string; ADMIN_BOOTSTRAP_TOKEN_SHA256?: string; }
const V48_ASSET_PATH = "/DTF_Studio_V48.22E_VIEW_ALL_SYNCED.html";
function isGetOrHead(request: Request): boolean { const method = request.method.toUpperCase(); return method === "GET" || method === "HEAD"; }
let currentAdminTraceStage="ADMIN-TRACE-00";
function adminTrace(stage: string, request: Request, extra: Record<string, unknown> = {}): void { currentAdminTraceStage=stage; console.log(JSON.stringify({ stage, path: new URL(request.url).pathname, method: request.method, ...extra })); }
function safeError(error: unknown): {type:string;message?:string} { const type=error instanceof Error?error.constructor.name:"UnknownError"; const raw=error instanceof Error?error.message:"Unexpected runtime failure"; return /password|secret|token|cookie|hash|salt|key|verifier/i.test(raw)?{type}:{type,message:raw.slice(0,160)}; }
function adminDiagnostic(stage: string, error: unknown, request: Request): Response { const id=crypto.randomUUID().slice(0,8); const detail=safeError(error); console.error(JSON.stringify({diagnosticId:id,stage,path:new URL(request.url).pathname,method:request.method,...detail})); return new Response(`<!doctype html><html><body><main><h1>DTF STUDIO ADMIN DIAGNOSTIC</h1><p>Diagnostic ID: ${id}</p><p>Failed Stage: ${stage}</p><p>Exception Type: ${detail.type}</p>${detail.message?`<p>Exception Message: ${detail.message}</p>`:""}</main></body></html>`,{status:500,headers:{"content-type":"text/html; charset=utf-8","cache-control":"no-store"}}); }
function isStaticRequest(pathname: string): boolean { return pathname.startsWith("/assets/") || pathname.includes(".") || pathname === "/robots.txt"; }
async function assetFetch(request: Request, env: Env, pathname: string): Promise<Response> { if (!env.ASSETS) return new Response("Static assets are not configured.", { status: 503 }); const url = new URL(request.url); url.pathname = pathname; url.search = ""; url.hash = ""; const response = await env.ASSETS.fetch(new Request(url, request)); if (response.status === 404) return new Response("Not found", { status: 404 }); return new Response(response.body, { status: response.status, statusText: response.statusText, headers: response.headers }); }

async function printifyRequest(env: Env, path: string): Promise<unknown> { if (!env.CONNECTIONS) throw new Error("Printify connection is not available."); const connections = createConnections(env as any); const entry = await (env.CONNECTIONS as any).find("printify"); const response = await connections[entry.alias].fetch(path, { method: "GET" }); if (!response.ok) throw new Error(`Printify request failed (${response.status}).`); return JSON.parse(await response.text()); }
function normalizeBlueprint(row: any) { const id=String(row?.id??row?.blueprint_id??''); if(!/^\d{1,20}$/.test(id)) return null; return { blueprintId:id,title:String(row.title??row.name??'').slice(0,300),description:String(row.description??'').slice(0,5000),productType:String(row.model??row.type??row.product_type??'').slice(0,120),source:row,variants:Array.isArray(row.variants)?row.variants:[],images:Array.isArray(row.images)?row.images:[],sourceAvailable:true,syncStatus:'synced' }; }
function parseBlueprintCatalog(text: string): any[] { try { const parsed=JSON.parse(text); const root=Array.isArray(parsed)?parsed:(parsed?.data??parsed?.items??parsed?.blueprints??[]); return Array.isArray(root)?root:[]; } catch { const items:any[]=[]; let start=-1,depth=0,inString=false,escaped=false; for(let i=0;i<text.length;i++){const ch=text[i]; if(inString){if(escaped)escaped=false; else if(ch==='\\')escaped=true; else if(ch==='"')inString=false; continue;} if(ch==='"'){inString=true;continue;} if(ch==='{'){if(depth===0)start=i;depth++;} else if(ch==='}'&&depth>0){depth--;if(depth===0&&start>=0){try{const item=JSON.parse(text.slice(start,i+1));if(item&&item.id!=null)items.push(item);}catch{} start=-1;}}} return items; } }
function catalogSlug(value: unknown): string { return String(value ?? "").toLowerCase().normalize("NFKD").replace(/[\u0300-\u036f]/g, "").replace(/&/g, " and ").replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "") || "other"; }
function buildCatalogCategories(products: any[]): any[] { const map=new Map<string,any>(); for(const p of products){ const name=String(p.categorySuggestion||"Other"), sub=String(p.subcategorySuggestion||"Other"), id=String(p.categoryId||catalogSlug(name)), subId=String(p.subcategoryId||catalogSlug(sub)); if(!map.has(id)) map.set(id,{id,name,count:0,subcategories:new Map<string,any>()}); const c=map.get(id); c.count++; if(!c.subcategories.has(subId)) c.subcategories.set(subId,{id:subId,name:sub,count:0}); c.subcategories.get(subId).count++; } return [...map.values()].map(c=>({id:c.id,name:c.name,count:c.count,subcategories:[...c.subcategories.values()].sort((a,b)=>a.name.localeCompare(b.name))})).sort((a,b)=>a.name.localeCompare(b.name)); }
async function loadPrintifySnapshot(request: Request, env: Env): Promise<any> {
  if (!env.ASSETS) throw new Error("Printify catalog snapshot assets are not configured.");
  const url = new URL("/data/printify-catalog.json", request.url);
  const response = await env.ASSETS.fetch(new Request(url, { method: "GET" }));
  if (!response.ok) throw new Error("Printify catalog snapshot is unavailable.");
  let snapshot: any; try { snapshot = await response.json(); } catch { throw new Error("Printify catalog snapshot is invalid JSON."); }
  if (snapshot?.schemaVersion !== 1 || snapshot?.source !== "printify-catalog-blueprints" || !Array.isArray(snapshot?.products) || snapshot.products.length === 0 || snapshot.total !== snapshot.products.length) throw new Error("Printify catalog snapshot failed validation.");
  for (const product of snapshot.products) { if (!/^(?:0|[1-9]\d*)$/.test(String(product?.blueprintId ?? "")) || !String(product?.title ?? "").trim()) throw new Error("Printify catalog snapshot contains an invalid product."); }
  return snapshot;
}
async function adminRbacApi(request: Request, env: Env): Promise<Response | null> {
  const url=new URL(request.url); if(!url.pathname.startsWith("/api/admin/rbac")) return null; const claims=await getAdminSessionClaims(request,env); const store=env.ITEMS.get(env.ITEMS.idFromName("default")); const identity=claims?await store.adminIdentity(claims.userId):null; if(!identity) return Response.json({ok:false,error:"Unauthorized"},{status:401}); const permission=request.method==="GET"?"access":"modify"; const resource=url.pathname.includes("/groups")?"admin.user_groups":"admin.users"; if(!await store.adminPermission(identity.id,resource,permission)) return Response.json({ok:false,error:"Permission denied."},{status:403});
  try { const method=request.method.toUpperCase(); if(method==="GET"&&url.pathname==="/api/admin/rbac/users") return Response.json({ok:true,users:await store.adminUsersDetailed()}); if(method==="GET"&&url.pathname==="/api/admin/rbac/groups") return Response.json({ok:true,groups:await store.adminGroups(),permissions:await store.adminPermissionMatrix("printing_technician")}); if(method==="GET"&&url.pathname==="/api/admin/rbac/audit") return Response.json({ok:true,audit:await store.adminAuditList()}); if(method==="POST"&&url.pathname==="/api/admin/rbac/users"){const body=await request.json() as any; const groupId=String(body.groupId||body.role||"group-printing-operator"); return Response.json({ok:true,user:await store.createAdminUserAsync(identity.id,String(body.username||""),String(body.password||""),groupId)});} if(method==="PATCH"&&/^\/api\/admin\/rbac\/users\/[^/]+\/group$/.test(url.pathname)){const id=url.pathname.split("/").slice(-2,-1)[0]||"";const body=await request.json() as any;return Response.json({ok:true,user:await store.setAdminUserGroup(identity.id,id,String(body.groupId||""))});} if(method==="PATCH"&&/^\/api\/admin\/rbac\/users\/[^/]+$/.test(url.pathname)){const id=url.pathname.split("/").pop()||"";const body=await request.json() as any;const result=body.role?await store.setAdminUserRole(identity.id,id,body.role==="main_admin"?"main_admin":"printing_technician"):await store.setAdminUserEnabled(identity.id,id,Boolean(body.enabled));return Response.json({ok:true,user:result});} return Response.json({ok:false,error:"Not found"},{status:404}); } catch(e){return Response.json({ok:false,error:e instanceof Error?e.message:"RBAC request failed"},{status:400});}
}

async function adminRbacGroupsApi(request: Request, env: Env): Promise<Response | null> { const url=new URL(request.url); if(!url.pathname.startsWith("/api/admin/rbac/groups")) return null; const claims=await getAdminSessionClaims(request,env); const store=env.ITEMS.get(env.ITEMS.idFromName("default")); const identity=claims?await store.adminIdentity(claims.userId):null; if(!identity) return Response.json({ok:false,error:"Unauthorized"},{status:401}); const permission=request.method==="GET"?"access":"modify"; if(!await store.adminPermission(identity.id,"admin.user_groups",permission)) return Response.json({ok:false,error:"Permission denied."},{status:403}); try { if(request.method==='GET'&&url.pathname==='/api/admin/rbac/groups') return Response.json({ok:true,groups:await store.adminGroupsDetailed()}); if(request.method==='GET'&&/^\/api\/admin\/rbac\/groups\/[^/]+\/permissions$/.test(url.pathname)) return Response.json({ok:true,permissions:await store.adminGroupPermissions(url.pathname.split('/').slice(-2,-1)[0])}); if(request.method==='PUT'&&/^\/api\/admin\/rbac\/groups\/[^/]+\/permissions$/.test(url.pathname)){const b=await request.json() as any;return Response.json({ok:true,permissions:await store.setAdminGroupPermissions(identity.id,url.pathname.split('/').slice(-2,-1)[0],Array.isArray(b.permissions)?b.permissions:[])});} if(request.method==='POST'&&url.pathname==='/api/admin/rbac/groups'){const b=await request.json() as any;return Response.json({ok:true,group:await store.createAdminGroup(identity.id,b.name)});} if(request.method==='PATCH'&&/^\/api\/admin\/rbac\/groups\/[^/]+$/.test(url.pathname)){const b=await request.json() as any;return Response.json({ok:true,group:await store.updateAdminGroup(identity.id,url.pathname.split('/').pop()!,b.name,b.enabled)});} if(request.method==='DELETE'&&/^\/api\/admin\/rbac\/groups\/[^/]+$/.test(url.pathname)){await store.deleteAdminGroup(identity.id,url.pathname.split('/').pop()!);return Response.json({ok:true});} if(request.method==='PATCH'&&/^\/api\/admin\/rbac\/users\/[^/]+\/group$/.test(url.pathname)){const b=await request.json() as any;return Response.json({ok:true,group:await store.setAdminUserGroup(identity.id,url.pathname.split('/').slice(-2,-1)[0],String(b.groupId||''))});} return Response.json({ok:false,error:'Not found'},{status:404}); } catch(e){return Response.json({ok:false,error:e instanceof Error?e.message:'RBAC group request failed'},{status:400});} }

async function adminAuditLogApi(request: Request, env: Env): Promise<Response | null> {
  const url=new URL(request.url);if(url.pathname!=="/api/admin/audit-log")return null;const claims=await getAdminSessionClaims(request,env);const store=env.ITEMS.get(env.ITEMS.idFromName("default"));const identity=claims?await store.adminIdentity(claims.userId):null;if(!identity)return Response.json({ok:false,error:"Unauthorized"},{status:401});if(!await store.adminPermission(identity.id,"admin.audit_log","access"))return Response.json({ok:false,error:"Permission denied."},{status:403});if(request.method!=="GET")return Response.json({ok:false,error:"Audit Log is read-only."},{status:405});try{return Response.json({ok:true,...await store.adminAuditLogs({search:url.searchParams.get("search")||"",action:url.searchParams.get("action")||"",resourceType:url.searchParams.get("resourceType")||"",actorId:url.searchParams.get("actorId")||"",dateFrom:url.searchParams.get("dateFrom")||"",dateTo:url.searchParams.get("dateTo")||"",page:Number(url.searchParams.get("page")||1),pageSize:Number(url.searchParams.get("pageSize")||25)}) as any});}catch(e){return Response.json({ok:false,error:e instanceof Error?e.message:"Audit Log request failed"},{status:400});}
}

async function adminIntegrationsApi(request: Request, env: Env): Promise<Response | null> {
  const url=new URL(request.url);if(!url.pathname.startsWith("/api/admin/integrations"))return null;const claims=await getAdminSessionClaims(request,env);const store=env.ITEMS.get(env.ITEMS.idFromName("default"));const identity=claims?await store.adminIdentity(claims.userId):null;if(!identity)return Response.json({ok:false,error:"Unauthorized"},{status:401});const method=request.method.toUpperCase(),permission=method==="GET"?"access":"modify";if(!await store.adminPermission(identity.id,"admin.integrations",permission))return Response.json({ok:false,error:"Permission denied."},{status:403});
  try{
    if(method==="GET"&&url.pathname==="/api/admin/integrations"){const data=await store.adminIntegrationsStatus();return Response.json({ok:true,data,runtime:{printifyConnectorConfigured:Boolean(env.CONNECTIONS),snapshotAssetsConfigured:Boolean(env.ASSETS)},canModify:await store.adminPermission(identity.id,"admin.integrations","modify")},{headers:{"cache-control":"no-store"}});}
    if(method==="POST"&&url.pathname==="/api/admin/integrations/printify/diagnose"){let connectorRegistered=false;if(env.CONNECTIONS){try{const entry=await (env.CONNECTIONS as any).find("printify");connectorRegistered=Boolean(entry?.alias);}catch{connectorRegistered=false;}}let snapshotValid=false,snapshotTotal:number|null=null,snapshotGeneratedAt:string|null=null;try{const snapshot=await loadPrintifySnapshot(request,env);snapshotValid=true;snapshotTotal=Number(snapshot.total||0);snapshotGeneratedAt=snapshot.generatedAt?String(snapshot.generatedAt):null;}catch{}return Response.json({ok:true,diagnostic:{connectorRegistered,snapshotValid,snapshotTotal,snapshotGeneratedAt,credentialsExposed:false}},{headers:{"cache-control":"no-store"}});}
    return Response.json({ok:false,error:"Method not allowed"},{status:405});
  }catch(e){return Response.json({ok:false,error:e instanceof Error?e.message:"Integrations request failed"},{status:400});}
}

async function adminSettingsApi(request: Request, env: Env): Promise<Response | null> {
  const url=new URL(request.url);if(url.pathname!=="/api/admin/settings")return null;const claims=await getAdminSessionClaims(request,env);const store=env.ITEMS.get(env.ITEMS.idFromName("default"));const identity=claims?await store.adminIdentity(claims.userId):null;if(!identity)return Response.json({ok:false,error:"Unauthorized"},{status:401});const method=request.method.toUpperCase(),permission=method==="GET"?"access":"modify";if(!await store.adminPermission(identity.id,"admin.settings",permission))return Response.json({ok:false,error:"Permission denied."},{status:403});try{const canModify=await store.adminPermission(identity.id,"admin.settings","modify");if(method==="GET")return Response.json({ok:true,...await store.businessSettingsSnapshot() as any,canModify});if(method==="PUT"){const body=await request.json() as any;return Response.json({ok:true,...await store.adminUpdateBusinessSettings(identity.id,body) as any,canModify:true});}return Response.json({ok:false,error:"Method not allowed"},{status:405});}catch(e){return Response.json({ok:false,error:e instanceof Error?e.message:"Settings request failed"},{status:400});}
}

async function publicBusinessSettingsApi(request: Request, env: Env): Promise<Response | null> {
  const url=new URL(request.url);if(url.pathname!=="/api/settings")return null;if(request.method!=="GET")return Response.json({ok:false,error:"Method not allowed"},{status:405});const store=env.ITEMS.get(env.ITEMS.idFromName("default"));try{const snapshot=await store.businessSettingsSnapshot() as any;return Response.json({ok:true,settings:snapshot.settings},{headers:{"cache-control":"no-store"}});}catch(e){return Response.json({ok:false,error:e instanceof Error?e.message:"Settings unavailable"},{status:500});}
}

async function adminPromotionsApi(request: Request, env: Env): Promise<Response | null> {
  const url=new URL(request.url);if(!url.pathname.startsWith("/api/admin/promotions"))return null;const claims=await getAdminSessionClaims(request,env);const store=env.ITEMS.get(env.ITEMS.idFromName("default"));const identity=claims?await store.adminIdentity(claims.userId):null;if(!identity)return Response.json({ok:false,error:"Unauthorized"},{status:401});const method=request.method.toUpperCase(),permission=method==="GET"?"access":"modify";if(!await store.adminPermission(identity.id,"admin.promotions",permission))return Response.json({ok:false,error:"Permission denied."},{status:403});
  try{const canModify=await store.adminPermission(identity.id,"admin.promotions","modify");if(method==="GET"&&url.pathname==="/api/admin/promotions")return Response.json({ok:true,...await store.adminPromotionsList({search:url.searchParams.get("search")||"",status:url.searchParams.get("status")||"",type:url.searchParams.get("type")||"",page:Number(url.searchParams.get("page")||1),pageSize:Number(url.searchParams.get("pageSize")||20)}) as any,canModify});if(method==="POST"&&url.pathname==="/api/admin/promotions"){const body=await request.json() as any;return Response.json({ok:true,promotion:await store.adminCreatePromotion(identity.id,body)});}const enableMatch=url.pathname.match(/^\/api\/admin\/promotions\/([^/]+)\/enabled$/);if(method==="PATCH"&&enableMatch){const body=await request.json() as any;return Response.json({ok:true,promotion:await store.adminSetPromotionEnabled(identity.id,decodeURIComponent(enableMatch[1]),Boolean(body.enabled))});}const detail=url.pathname.match(/^\/api\/admin\/promotions\/([^/]+)$/);if(detail){const id=decodeURIComponent(detail[1]);if(method==="GET"){const promotion=await store.adminPromotionDetail(id);return promotion?Response.json({ok:true,promotion,canModify}):Response.json({ok:false,error:"Promotion not found."},{status:404});}if(method==="PATCH"){const body=await request.json() as any;return Response.json({ok:true,promotion:await store.adminUpdatePromotion(identity.id,id,body)});}}return Response.json({ok:false,error:"Method not allowed"},{status:405});}catch(e){return Response.json({ok:false,error:e instanceof Error?e.message:"Promotions request failed"},{status:400});}
}

async function adminReportsApi(request: Request, env: Env): Promise<Response | null> {
  const url=new URL(request.url);if(url.pathname!=="/api/admin/reports")return null;const claims=await getAdminSessionClaims(request,env);const store=env.ITEMS.get(env.ITEMS.idFromName("default"));const identity=claims?await store.adminIdentity(claims.userId):null;if(!identity)return Response.json({ok:false,error:"Unauthorized"},{status:401});if(request.method!=="GET"){if(!await store.adminPermission(identity.id,"admin.reports","modify"))return Response.json({ok:false,error:"Permission denied."},{status:403});return Response.json({ok:false,error:"Reports are read-only."},{status:405});}if(!await store.adminPermission(identity.id,"admin.reports","access"))return Response.json({ok:false,error:"Permission denied."},{status:403});try{return Response.json({ok:true,report:await store.adminReports({dateFrom:url.searchParams.get("dateFrom")||"",dateTo:url.searchParams.get("dateTo")||""})});}catch(e){return Response.json({ok:false,error:e instanceof Error?e.message:"Reports request failed"},{status:400});}
}

async function adminPayoutsApi(request: Request, env: Env): Promise<Response | null> {
  const url=new URL(request.url);if(!url.pathname.startsWith("/api/admin/payouts"))return null;const claims=await getAdminSessionClaims(request,env);const store=env.ITEMS.get(env.ITEMS.idFromName("default"));const identity=claims?await store.adminIdentity(claims.userId):null;if(!identity)return Response.json({ok:false,error:"Unauthorized"},{status:401});const method=request.method.toUpperCase(),permission=method==="GET"?"access":"modify";if(!await store.adminPermission(identity.id,"admin.payouts",permission))return Response.json({ok:false,error:"Permission denied."},{status:403});
  try{const canModify=await store.adminPermission(identity.id,"admin.payouts","modify");if(method==="GET"&&url.pathname==="/api/admin/payouts")return Response.json({ok:true,...await store.adminPayoutsList({search:url.searchParams.get("search")||"",status:url.searchParams.get("status")||"",dateFrom:url.searchParams.get("dateFrom")||"",dateTo:url.searchParams.get("dateTo")||"",page:Number(url.searchParams.get("page")||1),pageSize:Number(url.searchParams.get("pageSize")||20)}) as any,canModify});const statusMatch=url.pathname.match(/^\/api\/admin\/payouts\/([^/]+)\/status$/);if(method==="PATCH"&&statusMatch){const body=await request.json() as any;return Response.json({ok:true,payout:await store.adminPayoutTransition(identity.id,decodeURIComponent(statusMatch[1]),String(body.status||""),String(body.note||""))});}const detail=url.pathname.match(/^\/api\/admin\/payouts\/([^/]+)$/);if(method==="GET"&&detail){const payout=await store.adminPayoutDetail(decodeURIComponent(detail[1]));return payout?Response.json({ok:true,payout,canModify}):Response.json({ok:false,error:"Withdrawal not found."},{status:404});}return Response.json({ok:false,error:"Method not allowed"},{status:405});}catch(e){return Response.json({ok:false,error:e instanceof Error?e.message:"Payouts request failed"},{status:400});}
}

async function adminDesignersApi(request: Request, env: Env): Promise<Response | null> {
  const url=new URL(request.url);if(!url.pathname.startsWith("/api/admin/designers"))return null;const claims=await getAdminSessionClaims(request,env);const store=env.ITEMS.get(env.ITEMS.idFromName("default"));const identity=claims?await store.adminIdentity(claims.userId):null;if(!identity)return Response.json({ok:false,error:"Unauthorized"},{status:401});const method=request.method.toUpperCase(),permission=method==="GET"?"access":"modify";if(!await store.adminPermission(identity.id,"admin.designers",permission))return Response.json({ok:false,error:"Permission denied."},{status:403});
  try{const canModify=await store.adminPermission(identity.id,"admin.designers","modify");if(method==="GET"&&url.pathname==="/api/admin/designers")return Response.json({ok:true,...await store.adminDesignersList({search:url.searchParams.get("search")||"",accountStatus:url.searchParams.get("accountStatus")||"",authorizationStatus:url.searchParams.get("authorizationStatus")||"",page:Number(url.searchParams.get("page")||1),pageSize:Number(url.searchParams.get("pageSize")||20)}) as any,canModify});const detail=url.pathname.match(/^\/api\/admin\/designers\/([^/]+)$/);if(detail){const id=decodeURIComponent(detail[1]);if(method==="GET"){const designer=await store.adminDesignerDetail(id);return designer?Response.json({ok:true,designer,canModify}):Response.json({ok:false,error:"Designer not found."},{status:404});}if(method==="PATCH"){const body=await request.json() as any;return Response.json({ok:true,designer:await store.adminUpdateDesignerAccount(identity.id,id,body)});}}return Response.json({ok:false,error:"Method not allowed"},{status:405});}catch(e){return Response.json({ok:false,error:e instanceof Error?e.message:"Designers request failed"},{status:400});}
}

async function adminCustomersApi(request: Request, env: Env): Promise<Response | null> {
  const url=new URL(request.url); if(!url.pathname.startsWith("/api/admin/customers")) return null;
  const claims=await getAdminSessionClaims(request,env); const store=env.ITEMS.get(env.ITEMS.idFromName("default")); const identity=claims?await store.adminIdentity(claims.userId):null;
  if(!identity) return Response.json({ok:false,error:"Unauthorized"},{status:401});
  const method=request.method.toUpperCase(),permission=method==="GET"?"access":"modify";
  if(!await store.adminPermission(identity.id,"admin.customers",permission)) return Response.json({ok:false,error:"Permission denied."},{status:403});
  try {
    const canModify=await store.adminPermission(identity.id,"admin.customers","modify");
    if(method==="GET"&&url.pathname==="/api/admin/customers") return Response.json({ok:true,...await store.adminCustomersList({search:url.searchParams.get("search")||"",status:url.searchParams.get("status")||"",dateFrom:url.searchParams.get("dateFrom")||"",dateTo:url.searchParams.get("dateTo")||"",page:Number(url.searchParams.get("page")||1),pageSize:Number(url.searchParams.get("pageSize")||20)}) as any,canModify});
    const detail=url.pathname.match(/^\/api\/admin\/customers\/([^/]+)$/);if(detail){const id=decodeURIComponent(detail[1]);if(method==="GET"){const customer=await store.adminCustomerDetail(id);return customer?Response.json({ok:true,customer,canModify}):Response.json({ok:false,error:"Customer not found."},{status:404});}if(method==="PATCH"){const body=await request.json() as any;return Response.json({ok:true,customer:await store.adminUpdateCustomer(identity.id,id,body)});}}
    return Response.json({ok:false,error:"Method not allowed"},{status:405});
  } catch(e){return Response.json({ok:false,error:e instanceof Error?e.message:"Customers request failed"},{status:400});}
}

async function adminProductsApi(request: Request, env: Env): Promise<Response | null> {
  const url=new URL(request.url); if(!url.pathname.startsWith("/api/admin/products") && !url.pathname.startsWith("/api/admin/catalog/categories") && !url.pathname.startsWith("/api/admin/catalog/subscription-plans") && !url.pathname.startsWith("/api/admin/catalog/filter-groups") && !url.pathname.startsWith("/api/admin/catalog/filters") && !url.pathname.startsWith("/api/admin/catalog/attribute-groups") && !url.pathname.startsWith("/api/admin/catalog/attributes") && !url.pathname.startsWith("/api/admin/catalog/options") && !url.pathname.startsWith("/api/admin/catalog/manufacturers") && !url.pathname.startsWith("/api/admin/catalog/identifiers") && !url.pathname.startsWith("/api/admin/catalog/downloads") && !url.pathname.startsWith("/api/admin/catalog/reviews") && !url.pathname.startsWith("/api/admin/catalog/information")) return null;
  const claims=await getAdminSessionClaims(request,env); const store=env.ITEMS.get(env.ITEMS.idFromName("default")); const identity=claims?await store.adminIdentity(claims.userId):null;
  if(!identity) return Response.json({ok:false,error:"Unauthorized"},{status:401});
  const method=request.method.toUpperCase(),permission=method==="GET"?"access":"modify";
  const catalogResource=url.pathname.startsWith("/api/admin/catalog/subscription-plans")?"admin.subscription_plans":url.pathname.startsWith("/api/admin/catalog/filter-groups")?"admin.filter_groups":url.pathname.startsWith("/api/admin/catalog/filters")?"admin.filters":url.pathname.startsWith("/api/admin/catalog/attribute-groups")?"admin.attribute_groups":url.pathname.startsWith("/api/admin/catalog/attributes")?"admin.attributes":url.pathname.startsWith("/api/admin/catalog/options")?"admin.options":url.pathname.startsWith("/api/admin/catalog/manufacturers")?"admin.manufacturers":url.pathname.startsWith("/api/admin/catalog/identifiers")?"admin.identifiers":url.pathname.startsWith("/api/admin/catalog/downloads")?"admin.downloads":url.pathname.startsWith("/api/admin/catalog/reviews")?"admin.reviews":url.pathname.startsWith("/api/admin/catalog/information")?"admin.information":"admin.products";
  if(!await store.adminPermission(identity.id,catalogResource,permission)) return Response.json({ok:false,error:"Permission denied."},{status:403});
  try {
    if(method==="GET"&&url.pathname==="/api/admin/catalog/categories") return Response.json({ok:true,...await store.adminCategoriesCatalog({search:url.searchParams.get("search")||"",status:url.searchParams.get("status")||"",page:Number(url.searchParams.get("page")||1),pageSize:Number(url.searchParams.get("pageSize")||20)}) as any});
    if(method==="GET"&&url.pathname==="/api/admin/catalog/subscription-plans") return Response.json({ok:true,...await store.adminSubscriptionPlans({search:url.searchParams.get("search")||"",status:url.searchParams.get("status")||"",page:Number(url.searchParams.get("page")||1),pageSize:Number(url.searchParams.get("pageSize")||20)}) as any});
    if(method==="GET"&&url.pathname==="/api/admin/catalog/downloads")return Response.json({ok:true,...await store.adminDownloads({search:url.searchParams.get("search")||"",page:Number(url.searchParams.get("page")||1),pageSize:Number(url.searchParams.get("pageSize")||20)}) as any});
    const downloadFileMatch=url.pathname.match(/^\/api\/admin\/catalog\/downloads\/([^/]+)\/file$/);if(method==="GET"&&downloadFileMatch){const file=await store.adminDownloadFile(decodeURIComponent(downloadFileMatch[1])) as any;if(!file)return Response.json({ok:false,error:"Download file is unavailable."},{status:404});const h=new Headers({"content-type":String(file.mimeType),"content-disposition":'attachment; filename="'+String(file.filename).replace(/["\r\n]/g,"_")+'"',"cache-control":"no-store"});return new Response(file.body,{headers:h});}
    if(method==="POST"&&url.pathname==="/api/admin/catalog/downloads"){const body=await request.formData(),file=body.get("file");const bytes=file instanceof File?await file.arrayBuffer():null;return Response.json({ok:true,download:await store.adminCreateDownload(identity.id,{nameEn:body.get("nameEn"),nameAr:body.get("nameAr"),filename:body.get("filename")||((file instanceof File)?file.name:""),mask:body.get("mask"),mimeType:file instanceof File?file.type:body.get("mimeType"),byteSize:file instanceof File?file.size:0},bytes)});}
    const downloadMatch=url.pathname.match(/^\/api\/admin\/catalog\/downloads\/([^/]+)$/);if(method==="PATCH"&&downloadMatch){const body=await request.formData();const file=body.get("file");const uploaded=file instanceof File;const bytes=uploaded?await file.arrayBuffer():null;const download=await store.adminCreateDownload(identity.id,{id:decodeURIComponent(downloadMatch[1]),nameEn:body.get("nameEn"),nameAr:body.get("nameAr"),filename:body.get("filename")||(uploaded?file.name:""),mask:body.get("mask"),mimeType:uploaded?file.type:body.get("mimeType"),byteSize:uploaded?file.size:0},bytes);return Response.json({ok:true,download});}if(method==="DELETE"&&downloadMatch)return Response.json({ok:true,...await store.adminDeleteDownload(identity.id,decodeURIComponent(downloadMatch[1])) as any});
    if(method==="GET"&&url.pathname==="/api/admin/catalog/reviews")return Response.json({ok:true,...await store.adminReviews() as any});
    if(method==="GET"&&url.pathname==="/api/admin/catalog/information")return Response.json({ok:true,...await store.adminInformation() as any});
    if(method==="POST"&&url.pathname==="/api/admin/catalog/information")return Response.json({ok:true,information:await store.adminUpsertInformation(identity.id,await request.json())});const infoMatch=url.pathname.match(/^\/api\/admin\/catalog\/information\/([^/]+)$/);if(method==="PATCH"&&infoMatch)return Response.json({ok:true,information:await store.adminUpsertInformation(identity.id,{...(await request.json() as Record<string, unknown>),id:decodeURIComponent(infoMatch[1])})});if(method==="DELETE"&&infoMatch)return Response.json({ok:true,...await store.adminDeleteInformation(identity.id,decodeURIComponent(infoMatch[1])) as any});
    if(method==="GET"&&url.pathname==="/api/admin/catalog/options") return Response.json({ok:true,...await store.adminOptions({search:url.searchParams.get("search")||"",page:Number(url.searchParams.get("page")||1),pageSize:Number(url.searchParams.get("pageSize")||20)}) as any});
    const optionDetailMatch=url.pathname.match(/^\/api\/admin\/catalog\/options\/([^/]+)$/);if(method==="GET"&&optionDetailMatch){const option=await store.adminOptionDetail(decodeURIComponent(optionDetailMatch[1]));return option?Response.json({ok:true,option}):Response.json({ok:false,error:"Option not found."},{status:404});}
    if(method==="POST"&&url.pathname==="/api/admin/catalog/options") return Response.json({ok:true,option:await store.adminUpsertOption(identity.id,await request.json())});
    const optionMatch=url.pathname.match(/^\/api\/admin\/catalog\/options\/([^/]+)$/);if(method==="PATCH"&&optionMatch)return Response.json({ok:true,option:await store.adminUpsertOption(identity.id,{...(await request.json() as Record<string, unknown>),id:decodeURIComponent(optionMatch[1])})});if(method==="DELETE"&&optionMatch)return Response.json({ok:true,...await store.adminDeleteOption(identity.id,decodeURIComponent(optionMatch[1])) as any});
    if(method==="GET"&&url.pathname==="/api/admin/catalog/manufacturers") return Response.json({ok:true,...await store.adminManufacturers() as any});if(method==="POST"&&url.pathname==="/api/admin/catalog/manufacturers")return Response.json({ok:true,manufacturer:await store.adminUpsertManufacturer(identity.id,await request.json())});const manufacturerMatch=url.pathname.match(/^\/api\/admin\/catalog\/manufacturers\/([^/]+)$/);if(method==="PATCH"&&manufacturerMatch)return Response.json({ok:true,manufacturer:await store.adminUpsertManufacturer(identity.id,{...(await request.json() as Record<string, unknown>),id:decodeURIComponent(manufacturerMatch[1])})});if(method==="DELETE"&&manufacturerMatch)return Response.json({ok:true,...await store.adminDeleteManufacturer(identity.id,decodeURIComponent(manufacturerMatch[1])) as any});
    if(method==="GET"&&url.pathname==="/api/admin/catalog/identifiers")return Response.json({ok:true,...await store.adminIdentifiers({search:url.searchParams.get("search")||"",page:Number(url.searchParams.get("page")||1),pageSize:Number(url.searchParams.get("pageSize")||20)}) as any});if(method==="POST"&&url.pathname==="/api/admin/catalog/identifiers")return Response.json({ok:true,identifier:await store.adminUpsertIdentifier(identity.id,await request.json())});const identifierMatch=url.pathname.match(/^\/api\/admin\/catalog\/identifiers\/([^/]+)$/);if(method==="PATCH"&&identifierMatch)return Response.json({ok:true,identifier:await store.adminUpsertIdentifier(identity.id,{...(await request.json() as Record<string, unknown>),id:decodeURIComponent(identifierMatch[1])})});if(method==="DELETE"&&identifierMatch)return Response.json({ok:true,...await store.adminDeleteIdentifier(identity.id,decodeURIComponent(identifierMatch[1])) as any});
    if(method==="GET"&&url.pathname==="/api/admin/catalog/attribute-groups") return Response.json({ok:true,...await store.adminAttributeGroups({search:url.searchParams.get("search")||"",page:Number(url.searchParams.get("page")||1),pageSize:Number(url.searchParams.get("pageSize")||20)}) as any});
    if(method==="POST"&&url.pathname==="/api/admin/catalog/attribute-groups") return Response.json({ok:true,group:await store.adminUpsertAttributeGroup(identity.id,await request.json())});
    const attributeGroupMatch=url.pathname.match(/^\/api\/admin\/catalog\/attribute-groups\/([^/]+)$/);if(method==="PATCH"&&attributeGroupMatch)return Response.json({ok:true,group:await store.adminUpsertAttributeGroup(identity.id,{...(await request.json() as Record<string, unknown>),id:decodeURIComponent(attributeGroupMatch[1])})});if(method==="DELETE"&&attributeGroupMatch)return Response.json({ok:true,...await store.adminDeleteAttributeGroup(identity.id,decodeURIComponent(attributeGroupMatch[1])) as any});
    if(method==="GET"&&url.pathname==="/api/admin/catalog/attributes") return Response.json({ok:true,...await store.adminAttributes({search:url.searchParams.get("search")||"",groupId:url.searchParams.get("groupId")||"",page:Number(url.searchParams.get("page")||1),pageSize:Number(url.searchParams.get("pageSize")||20)}) as any});
    if(method==="POST"&&url.pathname==="/api/admin/catalog/attributes") return Response.json({ok:true,attribute:await store.adminUpsertAttribute(identity.id,await request.json())});
    const attributeMatch=url.pathname.match(/^\/api\/admin\/catalog\/attributes\/([^/]+)$/);if(method==="PATCH"&&attributeMatch)return Response.json({ok:true,attribute:await store.adminUpsertAttribute(identity.id,{...(await request.json() as Record<string, unknown>),id:decodeURIComponent(attributeMatch[1])})});if(method==="DELETE"&&attributeMatch)return Response.json({ok:true,...await store.adminDeleteAttribute(identity.id,decodeURIComponent(attributeMatch[1])) as any});
    if(method==="GET"&&url.pathname==="/api/admin/catalog/filter-groups") return Response.json({ok:true,...await store.adminFilterGroups({search:url.searchParams.get("search")||"",page:Number(url.searchParams.get("page")||1),pageSize:Number(url.searchParams.get("pageSize")||20)}) as any});
    if(method==="POST"&&url.pathname==="/api/admin/catalog/filter-groups") return Response.json({ok:true,group:await store.adminUpsertFilterGroup(identity.id,await request.json())});
    const filterGroupMatch=url.pathname.match(/^\/api\/admin\/catalog\/filter-groups\/([^/]+)$/);if(method==="PATCH"&&filterGroupMatch)return Response.json({ok:true,group:await store.adminUpsertFilterGroup(identity.id,{...(await request.json() as Record<string, unknown>),id:decodeURIComponent(filterGroupMatch[1])})});if(method==="DELETE"&&filterGroupMatch)return Response.json({ok:true,...await store.adminDeleteFilterGroup(identity.id,decodeURIComponent(filterGroupMatch[1])) as any});
    if(method==="GET"&&url.pathname==="/api/admin/catalog/filters") return Response.json({ok:true,...await store.adminFilters({search:url.searchParams.get("search")||"",groupId:url.searchParams.get("groupId")||"",page:Number(url.searchParams.get("page")||1),pageSize:Number(url.searchParams.get("pageSize")||20)}) as any});
    if(method==="POST"&&url.pathname==="/api/admin/catalog/filters") return Response.json({ok:true,filter:await store.adminUpsertFilter(identity.id,await request.json())});
    const filterMatch=url.pathname.match(/^\/api\/admin\/catalog\/filters\/([^/]+)$/);if(method==="PATCH"&&filterMatch)return Response.json({ok:true,filter:await store.adminUpsertFilter(identity.id,{...(await request.json() as Record<string, unknown>),id:decodeURIComponent(filterMatch[1])})});if(method==="DELETE"&&filterMatch)return Response.json({ok:true,...await store.adminDeleteFilter(identity.id,decodeURIComponent(filterMatch[1])) as any});
    if(method==="POST"&&url.pathname==="/api/admin/catalog/subscription-plans") return Response.json({ok:true,plan:await store.adminUpsertSubscriptionPlan(identity.id,await request.json())});
    const planCopyMatch=url.pathname.match(/^\/api\/admin\/catalog\/subscription-plans\/([^/]+)\/copy$/);
    if(method==="POST"&&planCopyMatch) return Response.json({ok:true,plan:await store.adminCopySubscriptionPlan(identity.id,decodeURIComponent(planCopyMatch[1]))});
    const planMatch=url.pathname.match(/^\/api\/admin\/catalog\/subscription-plans\/([^/]+)$/);
    if(method==="PATCH"&&planMatch) return Response.json({ok:true,plan:await store.adminUpsertSubscriptionPlan(identity.id,{...(await request.json() as Record<string, unknown>),id:decodeURIComponent(planMatch[1])})});
    if(method==="DELETE"&&planMatch) return Response.json({ok:true,...await store.adminDeleteSubscriptionPlan(identity.id,decodeURIComponent(planMatch[1])) as any});
    if(method==="GET"&&url.pathname==="/api/admin/catalog/categories/autocomplete") return Response.json({ok:true,items:await store.adminCategoryAutocomplete(url.searchParams.get("search")||"")});
    if(method==="GET"&&url.pathname==="/api/admin/catalog/categories/filter-options") return Response.json({ok:true,items:await store.adminCategoryFilterOptions(url.searchParams.get("search")||"")});
    if(method==="POST"&&url.pathname==="/api/admin/catalog/categories"){const b=await request.json() as any;return Response.json({ok:true,category:await store.adminUpsertProductCategory(identity.id,b)});}
    const catalogCategoryMatch=url.pathname.match(/^\/api\/admin\/catalog\/categories\/([^/]+)$/);
    if(method==="GET"&&catalogCategoryMatch){const category=await store.adminCategoryDetail(decodeURIComponent(catalogCategoryMatch[1]));return category?Response.json({ok:true,category}):Response.json({ok:false,error:"Category not found."},{status:404});}
    if(method==="PATCH"&&catalogCategoryMatch){const b=await request.json() as any;return Response.json({ok:true,category:await store.adminUpsertProductCategory(identity.id,{...b,id:decodeURIComponent(catalogCategoryMatch[1])})});}
    if(method==="DELETE"&&catalogCategoryMatch){return Response.json({ok:true,...await store.adminDeleteProductCategory(identity.id,decodeURIComponent(catalogCategoryMatch[1])) as any});}
    if(method==="GET"&&url.pathname==="/api/admin/products") return Response.json({ok:true,...await store.adminProductsCatalog({search:url.searchParams.get("search")||"",category:url.searchParams.get("category")||"",source:url.searchParams.get("source")||"",enabled:url.searchParams.get("enabled")||"",published:url.searchParams.get("published")||"",model:url.searchParams.get("model")||"",priceFrom:url.searchParams.get("priceFrom")||"",priceTo:url.searchParams.get("priceTo")||"",quantityFrom:url.searchParams.get("quantityFrom")||"",quantityTo:url.searchParams.get("quantityTo")||"",sort:url.searchParams.get("sort")||"name",order:url.searchParams.get("order")||"asc",page:Number(url.searchParams.get("page")||1),pageSize:Number(url.searchParams.get("pageSize")||20)}) as any});
    if(method==="POST"&&url.pathname==="/api/admin/products"){const b=await request.json() as any;return Response.json({ok:true,product:await store.adminCreateProduct(identity.id,b)});}
    if(method==="POST"&&url.pathname==="/api/admin/products/categories"){const b=await request.json() as any;return Response.json({ok:true,category:await store.adminUpsertProductCategory(identity.id,b)});}
    const categoryMatch=url.pathname.match(/^\/api\/admin\/products\/categories\/([^/]+)$/);if(method==="PATCH"&&categoryMatch){const b=await request.json() as any;return Response.json({ok:true,category:await store.adminUpsertProductCategory(identity.id,{...b,id:decodeURIComponent(categoryMatch[1])})});}
    const publishMatch=url.pathname.match(/^\/api\/admin\/products\/([^/]+)\/publish$/);if(method==="PATCH"&&publishMatch){const b=await request.json() as any;return Response.json({ok:true,product:await store.adminSetProductPublished(identity.id,decodeURIComponent(publishMatch[1]),Boolean(b.published))});}
    const variantsMatch=url.pathname.match(/^\/api\/admin\/products\/([^/]+)\/variants$/);if(method==="POST"&&variantsMatch){const b=await request.json() as any;return Response.json({ok:true,product:await store.adminUpsertProductVariant(identity.id,decodeURIComponent(variantsMatch[1]),b)});}
    const eligibilityMatch=url.pathname.match(/^\/api\/admin\/products\/([^/]+)\/eligibility$/);if(method==="PUT"&&eligibilityMatch){const b=await request.json() as any;return Response.json({ok:true,product:await store.adminProductSetEligibility(identity.id,decodeURIComponent(eligibilityMatch[1]),Array.isArray(b.types)?b.types:[])});}
    const mediaMatch=url.pathname.match(/^\/api\/admin\/products\/([^/]+)\/media$/);if(method==="POST"&&mediaMatch){const b=await request.json() as any;return Response.json({ok:true,product:await store.adminProductMediaAdd(identity.id,decodeURIComponent(mediaMatch[1]),b)});}
    const mediaDelete=url.pathname.match(/^\/api\/admin\/products\/([^/]+)\/media\/([^/]+)$/);if(method==="DELETE"&&mediaDelete)return Response.json({ok:true,product:await store.adminProductMediaRemove(identity.id,decodeURIComponent(mediaDelete[1]),decodeURIComponent(mediaDelete[2]))});
    const detailMatch=url.pathname.match(/^\/api\/admin\/products\/([^/]+)$/);if(detailMatch&&decodeURIComponent(detailMatch[1])!=="categories"){const id=decodeURIComponent(detailMatch[1]);if(method==="GET"){const product=await store.adminProductDetail(id);return product?Response.json({ok:true,product}):Response.json({ok:false,error:"Product not found."},{status:404});}if(method==="PATCH"){const b=await request.json() as any;return Response.json({ok:true,product:await store.adminUpdateProduct(identity.id,id,b)});}}
    return Response.json({ok:false,error:"Method not allowed"},{status:405});
  } catch(e){return Response.json({ok:false,error:e instanceof Error?e.message:"Products request failed"},{status:400});}
}

async function adminManualReviewApi(request: Request, env: Env): Promise<Response | null> {
  const url=new URL(request.url); if(!url.pathname.startsWith("/api/admin/manual-review")) return null;
  const claims=await getAdminSessionClaims(request,env); const store=env.ITEMS.get(env.ITEMS.idFromName("default")); const identity=claims?await store.adminIdentity(claims.userId):null;
  if(!identity) return Response.json({ok:false,error:"Unauthorized"},{status:401});
  const method=request.method.toUpperCase(); const permission=method==="GET"?"access":"modify";
  if(!await store.adminPermission(identity.id,"admin.manual_review",permission)) return Response.json({ok:false,error:"Permission denied."},{status:403});
  try {
    const canModify=await store.adminPermission(identity.id,"admin.manual_review","modify");
    if(method==="GET"&&url.pathname==="/api/admin/manual-review") return Response.json({ok:true,...await store.adminManualReviewQueues() as any,canModify});
    const qualificationMatch=url.pathname.match(/^\/api\/admin\/manual-review\/qualifications\/([^/]+)$/);
    if(method==="GET"&&qualificationMatch){const application=await store.adminQualificationReviewDetail(decodeURIComponent(qualificationMatch[1]));return application?Response.json({ok:true,application,canModify}):Response.json({ok:false,error:"Qualification application not found."},{status:404});}
    if(method==="PATCH"&&qualificationMatch){const body=await request.json() as any;const decision=body.decision==="approve"?"approve":"reject";return Response.json({ok:true,application:await store.adminQualificationReviewDecision(identity.id,decodeURIComponent(qualificationMatch[1]),decision,String(body.reason||""))});}
    const designMatch=url.pathname.match(/^\/api\/admin\/manual-review\/designs\/([^/]+)$/);
    if(method==="PATCH"&&designMatch){const body=await request.json() as any;const decision=body.decision==="approve"?"approve":"reject";return Response.json({ok:true,design:await store.adminDesignReviewDecision(identity.id,decodeURIComponent(designMatch[1]),decision,String(body.reason||""))});}
    return Response.json({ok:false,error:"Method not allowed"},{status:405});
  } catch(e){return Response.json({ok:false,error:e instanceof Error?e.message:"Manual Review request failed"},{status:400});}
}

async function adminProductionApi(request: Request, env: Env): Promise<Response | null> {
  const url=new URL(request.url); if(!url.pathname.startsWith("/api/admin/production")) return null;
  const claims=await getAdminSessionClaims(request,env); const store=env.ITEMS.get(env.ITEMS.idFromName("default")); const identity=claims?await store.adminIdentity(claims.userId):null;
  if(!identity) return Response.json({ok:false,error:"Unauthorized"},{status:401});
  const permission=request.method.toUpperCase()==="GET"?"access":"modify";
  if(!await store.adminPermission(identity.id,"admin.production",permission)) return Response.json({ok:false,error:"Permission denied."},{status:403});
  try {
    const method=request.method.toUpperCase();
    if(method==="GET"&&url.pathname==="/api/admin/production") return Response.json({ok:true,...await store.adminProductionQueue({search:url.searchParams.get("search")||"",status:url.searchParams.get("status")||"",page:Number(url.searchParams.get("page")||1),pageSize:Number(url.searchParams.get("pageSize")||20)}) as any});
    const masterMatch=url.pathname.match(/^\/api\/admin\/production\/jobs\/([^/]+)\/master$/);
    if(method==="GET"&&masterMatch){const asset=await store.adminProductionMasterAsset(decodeURIComponent(masterMatch[1])) as any;if(!env.ASSETS)return Response.json({ok:false,error:"Master file storage is unavailable in this runtime."},{status:503});const key=String(asset.storageKey||"").replace(/^\/+|^public\//g,"");if(!key||key.includes(".."))return Response.json({ok:false,error:"Invalid master storage key."},{status:400});const file=await env.ASSETS.fetch(new Request(new URL("/"+key,request.url),{method:"GET"}));if(!file.ok)return Response.json({ok:false,error:"Approved master file bytes are unavailable in configured assets storage."},{status:404});const headers=new Headers(file.headers);headers.set("content-type",String(asset.mimeType||file.headers.get("content-type")||"application/octet-stream"));headers.set("content-disposition",'attachment; filename="'+String(asset.filename||"ready-to-print-master").replace(/["\r\n]/g,"_")+'"');headers.set("cache-control","no-store");return new Response(file.body,{status:200,headers});}
    const statusMatch=url.pathname.match(/^\/api\/admin\/production\/jobs\/([^/]+)\/status$/);if(method==="PATCH"&&statusMatch){const body=await request.json() as any;return Response.json({ok:true,job:await store.adminProductionUpdateStatus(identity.id,decodeURIComponent(statusMatch[1]),String(body.status||""))});}
    const detailMatch=url.pathname.match(/^\/api\/admin\/production\/jobs\/([^/]+)$/);if(method==="GET"&&detailMatch){const job=await store.adminProductionJob(decodeURIComponent(detailMatch[1]));return job?Response.json({ok:true,job}):Response.json({ok:false,error:"Printing job not found."},{status:404});}
    return Response.json({ok:false,error:"Method not allowed"},{status:405});
  } catch(e){return Response.json({ok:false,error:e instanceof Error?e.message:"Production request failed"},{status:400});}
}

async function adminOrdersApi(request: Request, env: Env): Promise<Response | null> {
  const url=new URL(request.url); if(!url.pathname.startsWith("/api/admin/orders")) return null;
  const claims=await getAdminSessionClaims(request,env); const store=env.ITEMS.get(env.ITEMS.idFromName("default")); const identity=claims?await store.adminIdentity(claims.userId):null;
  if(!identity) return Response.json({ok:false,error:"Unauthorized"},{status:401});
  const permission=request.method.toUpperCase()==="GET"?"access":"modify";
  if(!await store.adminPermission(identity.id,"admin.orders",permission)) return Response.json({ok:false,error:"Permission denied."},{status:403});
  try {
    const method=request.method.toUpperCase();

[Showing lines 1-200 of 548. Use offset=201 to continue.]